// News Database (Auto-generated by KoraLegend Scraper — kooora.com)
// Last updated: 2026-06-11T21:40:01.884Z
const newsDatabase = {
    "en": {
        "all": [
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "سابقة تاريخية.. المكسيك تكسر عقدتين بعد 96 عامًا",
                "description": "المكسيك بدأت حملتها بنجاح استثنائي",
                "date": "12 يونيو 2026 00:38",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280431821/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2280431821.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B3%D8%A7%D8%A8%D9%82%D8%A9-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A%D8%A9--%D8%A7%D9%84%D9%85%D9%83%D8%B3%D9%8A%D9%83-%D8%AA%D9%83%D8%B3%D8%B1-%D8%B9%D9%82%D8%AF%D8%AA%D9%8A%D9%86-%D8%A8%D8%B9%D8%AF-96-%D8%B9%D8%A7%D9%85%D9%8B%D8%A7/bltdea3b07097298f46"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "افتتاح مونديال 2026 الأكثر احمرارًا في التاريخ",
                "description": "المكسيك استغلت النقص العددي لجنوب إفريقيا",
                "date": "12 يونيو 2026 00:19",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281126711/crop/MM5DGMZTGE5DCOBXGQ5G433XMU5DAORRG42A====/GettyImages-2281126711.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-2026-%D8%A7%D9%84%D8%A7%D9%94%D9%83%D8%AB%D8%B1-%D8%A7%D8%AD%D9%85%D8%B1%D8%A7%D8%B1%D9%8B%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE/bltaab086e20d8ea447"
            },
            {
                "category": "جنوب أفريقيا",
                "title": "بالفيديو.. لعنة إفريقية تضرب افتتاح مونديال 2026",
                "description": "ماذا حدث في مونديال 1990",
                "date": "12 يونيو 2026 00:16",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280453292/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2280453292.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88--%D9%84%D8%B9%D9%86%D8%A9-%D8%A7%D9%84%D9%83%D8%A7%D9%85%D9%8A%D8%B1%D9%88%D9%86-%D8%AA%D8%B6%D8%B1%D8%A8-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%95%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7-%D9%81%D9%8A-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt87f2ad20d3e29e21"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "كينيونيس يدخل تاريخ كأس العالم برقم مذهل",
                "description": "نجم القادسية يصنع الحدث",
                "date": "12 يونيو 2026 00:10",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281123803/crop/MM5DGOJWGA5DEMRSHA5G433XMU5DAORSGA3A====/GettyImages-2281123803.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%83%D9%8A%D9%86%D9%8A%D9%88%D9%86%D9%8A%D8%B3-%D9%8A%D8%AF%D8%AE%D9%84-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-%D8%A8%D8%B1%D9%82%D9%85-%D9%85%D8%B0%D9%87%D9%84/blt6312a8da462a5747"
            },
            {
                "category": "كأس العالم",
                "title": "جدول ترتيب هدافي كأس العالم 2026",
                "description": "تعرف على جدول ترتيب هدافي كأس العالم 2026\n",
                "date": "12 يونيو 2026 00:10",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/blt2a471b58a2988371/GOAL%20-%20Multiple%20Images%20-%204%20Split%20-%20Facebook%20(1).jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AC%D8%AF%D9%88%D9%84-%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D9%87%D8%AF%D8%A7%D9%81%D9%8A-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026/blt322432cc8cc2c1f3"
            },
            {
                "category": "الولايات المتحدة الأمريكية",
                "title": "ترتيب مجموعات كأس العالم 2026 .. جدول المباريات والقنوات الناقلة",
                "description": "تعرف على ترتيب مجموعات بطولة كأس العالم 2026 وجدول المباريات..",
                "date": "12 يونيو 2026 00:09",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2250177089/crop/MM5DKMBQGU5DEOBRGU5G433XMU5DAORSGYYA====/GettyImages-2250177089.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A7%D8%AA-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026-%D8%AC%D8%AF%D9%88%D9%84-%D8%A7%D9%84%D9%85%D8%A8%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D9%82%D9%86%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D9%86%D8%A7%D9%82%D9%84%D8%A9/blt2c98b99c5228b2c9"
            },
            {
                "category": "الولايات المتحدة الأمريكية",
                "title": "جدول مباريات كأس العالم 2026 .. والقنوات الناقلة",
                "description": "تعرف على موعد كأس العالم 2026 وجدول المباريات وترتيب المجموعات والنتائج وجميع القنوات الناقلة للبطولة..",
                "date": "12 يونيو 2026 00:07",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2249518198/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DINZQHIYTAOBT/GettyImages-2249518198.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/-%D8%AC%D8%AF%D9%88%D9%84-%D9%85%D8%A8%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D8%A7%D9%84%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A7%D8%AA-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026-%D8%A7%D9%84%D9%82%D9%86%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D9%86%D8%A7%D9%82%D9%84%D8%A9-/blte65707120dfb3330"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "افتتاح أحمر.. المكسيك تدشن المونديال بقهر جنوب أفريقيا",
                "description": "افتتاح أحمر.. المكسيك تدشن المونديال بقهر جنوب أفريقيا",
                "date": "12 يونيو 2026 00:06",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281126711/crop/MM5DEMBQGA5DCMJSGU5G433XMU5DCMJTHA5DEMRR/GettyImages-2281126711.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%94%D8%AD%D9%85%D8%B1--%D8%A7%D9%84%D9%85%D9%83%D8%B3%D9%8A%D9%83-%D8%AA%D8%AF%D8%B4%D9%86-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-%D8%A8%D9%82%D9%87%D8%B1-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7/bltd34abf5688e26504"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "فيديو: دموع الفرح.. خيمينيز يقتل جنوب أفريقيا بهدف تاريخي",
                "description": "هدف يحسم المباراة",
                "date": "12 يونيو 2026 00:01",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltb031673ef03a8e03/crop/MM5DCNZRGI5DSNRTHJXG653FHIYTAMR2GY======/GOAL%20-%20Blank%20WEB%20-%20Facebook%20(31).jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D8%AF%D9%85%D9%88%D8%B9-%D8%A7%D9%84%D9%81%D8%B1%D8%AD--%D8%AE%D9%8A%D9%85%D9%8A%D9%86%D9%8A%D8%B2-%D9%8A%D9%82%D8%AA%D9%84-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7-%D8%A8%D9%87%D8%AF%D9%81-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A/bltfef3d14e8c873360"
            },
            {
                "category": "كأس العالم",
                "title": "جدول مباريات اليوم الجمعة 12 يونيو 2026 في كأس العالم ..القنوات الناقلة والمعلقين",
                "description": "تعرف على مباريات اليوم والقنوات الناقلة وجدول المعلقين\n",
                "date": "12 يونيو 2026 00:00",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltcd07742c13987629/world%20cup%20trophy%20(8).jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AC%D8%AF%D9%88%D9%84-%D9%85%D8%A8%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%AC%D9%85%D8%B9%D8%A9-12-%D9%8A%D9%88%D9%86%D9%8A%D9%88-2026-%D9%81%D9%8A-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85--%D8%A7%D9%84%D9%82%D9%86%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D9%86%D8%A7%D9%82%D9%84%D8%A9-%D9%88%D8%A7%D9%84%D9%85%D8%B9%D9%84%D9%82%D9%8A%D9%86/blt07025fc2b907377a"
            },
            {
                "category": "ستال سولباكين",
                "title": "\"كلنا منافقون\".. مدرب النرويج يهز مونديال أمريكا قبل مواجهة العراق",
                "description": "يرفض مع حدث مع المهاجم أيمن حسين",
                "date": "11 يونيو 2026 23:43",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2279518680/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2279518680.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%83%D9%84%D9%86%D8%A7-%D9%85%D9%86%D8%A7%D9%81%D9%82%D9%88%D9%86--%D9%85%D8%AF%D8%B1%D8%A8-%D8%A7%D9%84%D9%86%D8%B1%D9%88%D9%8A%D8%AC-%D9%8A%D9%87%D8%B2-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-%D8%A7%D9%94%D9%85%D8%B1%D9%8A%D9%83%D8%A7-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D8%A7%D8%AC%D9%87%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82/blt52166b4ee8bf4bdb"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "فيديو: فخ برشلونة يبتلع جنوب أفريقيا في افتتاح كأس العالم 2026",
                "description": "صدمة جديدة تصعق \"البافانا بافانا\"",
                "date": "11 يونيو 2026 23:43",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281122685/crop/MM5DGMBVGQ5DCNZRHA5G433XMU5DAORRGU4Q====/GettyImages-2281122685.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%81%D8%AE-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%8A%D8%A8%D8%AA%D9%84%D8%B9-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7-%D9%81%D9%8A-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026/bltbb3cd963a34b451b"
            },
            {
                "category": "ريال مدريد",
                "title": "ماذا قال برشلونة لبرناردو سيلفا قبل موافقته على عرض ريال مدريد؟",
                "description": "البارسا أوضح ثوابته للبرتغالي",
                "date": "11 يونيو 2026 23:39",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltc8e411517cf48100/crop/MM5DGOJTGY5DEMRRGQ5G433XMU5DAORTGMZA====/GettyImages-2277559471.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D8%A7%D8%B0%D8%A7-%D9%82%D8%A7%D9%84-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%84%D8%A8%D8%B1%D9%86%D8%A7%D8%B1%D8%AF%D9%88-%D8%B3%D9%8A%D9%84%D9%81%D8%A7-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D8%A7%D9%81%D9%82%D8%AA%D9%87-%D8%B9%D9%84%D9%89-%D8%B9%D8%B1%D8%B6-%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF/blt200668ab5ec6b48d"
            },
            {
                "category": "ريال مدريد",
                "title": "تفاصيل الصفقة.. ريال مدريد يتوصل لاتفاق مع برناردو سيلفا",
                "description": "البرتغالي المخضرم بات على أبواب الريال",
                "date": "11 يونيو 2026 23:02",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280476588/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2280476588.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D9%81%D8%A7%D8%B5%D9%8A%D9%84-%D8%A7%D9%84%D8%B5%D9%81%D9%82%D8%A9--%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF-%D9%8A%D8%AA%D9%88%D8%B5%D9%84-%D9%84%D8%A7%D8%AA%D9%81%D8%A7%D9%82-%D9%85%D8%B9-%D8%A8%D8%B1%D9%86%D8%A7%D8%B1%D8%AF%D9%88-%D8%B3%D9%8A%D9%84%D9%81%D8%A7/blt302ed5ba7f79e3a8"
            },
            {
                "category": "المكسيك",
                "title": "بالفيديو: \"دائرة فيفا\" تقتل الخط المعهود.. طقس جديد في مونديال 2026",
                "description": "كيف تم عزف النشيد الوطني في افتتاح كأس العالم؟",
                "date": "11 يونيو 2026 23:00",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281115352/crop/MM5DIOJWGA5DENZZGA5G433XMU5DGMR2GA======/GettyImages-2281115352.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88--%D8%AF%D8%A7%D9%8A%D9%94%D8%B1%D8%A9-%D9%81%D9%8A%D9%81%D8%A7-%D8%AA%D9%82%D8%AA%D9%84-%D8%A7%D9%84%D8%AE%D8%B7-%D8%A7%D9%84%D9%85%D8%B9%D9%87%D9%88%D8%AF--%D8%B7%D9%82%D8%B3-%D8%AC%D8%AF%D9%8A%D8%AF-%D9%81%D9%8A-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-2026/blt050ba69b9547f71a"
            },
            {
                "category": "خوليان كينيونيس",
                "title": "فيديو: من روشن إلى العالم.. كينيونيس يقص شريط أهداف المونديال",
                "description": "نجم المكسيك يسجل أول أهداف المونديال",
                "date": "11 يونيو 2026 22:35",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280535466/crop/MM5DKMBQGM5DEOBRGQ5G433XMU5DAORSGYYQ====/GettyImages-2280535466.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%85%D9%86-%D8%B1%D9%88%D8%B4%D9%86-%D8%A7%D9%95%D9%84%D9%89-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85--%D9%83%D9%8A%D9%86%D9%8A%D9%88%D9%86%D9%8A%D8%B3-%D9%8A%D9%82%D8%B5-%D8%B4%D8%B1%D9%8A%D8%B7-%D8%A7%D9%94%D9%87%D8%AF%D8%A7%D9%81-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt3676342de6ab161c"
            },
            {
                "category": "كأس العالم",
                "title": "بالفيديو.. إنفانتينو يصدم أوروبا: قطر أفضل دولة استضافت المونديال",
                "description": "بالفيديو.. إنفانتينو يصدم أوروبا: قطر أفضل دولة استضافت المونديال",
                "date": "11 يونيو 2026 22:31",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281117063/crop/MM5DCMRUHA5DOMBSHJXG653FHIYTCNB2GE2DI===/GettyImages-2281117063.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88--%D8%A7%D9%95%D9%86%D9%81%D8%A7%D9%86%D8%AA%D9%8A%D9%86%D9%88-%D9%8A%D8%B5%D8%AF%D9%85-%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D8%A7-%D9%82%D8%B7%D8%B1-%D8%A7%D9%94%D9%81%D8%B6%D9%84-%D8%AF%D9%88%D9%84%D8%A9-%D8%A7%D8%B3%D8%AA%D8%B6%D8%A7%D9%81%D8%AA-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt839e2b330958d567"
            },
            {
                "category": "نيكولاس تاجليافيكو",
                "title": "توتر في معسكر الأرجنتين.. تقرير طبي يُربك حسابات سكالوني قبل مواجهة الجزائر",
                "description": "هل يواجه \"محاربو الصحراء\" دون أحد ركائز \"التانجو\"؟",
                "date": "11 يونيو 2026 22:28",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2267943815/crop/MM5DGNRZGY5DEMBXHE5G433XMU5DAORXGI======/GettyImages-2267943815.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D9%88%D8%AA%D8%B1-%D9%81%D9%8A-%D9%85%D8%B9%D8%B3%D9%83%D8%B1-%D8%A7%D9%84%D8%A7%D9%94%D8%B1%D8%AC%D9%86%D8%AA%D9%8A%D9%86--%D8%AA%D9%82%D8%B1%D9%8A%D8%B1-%D8%B7%D8%A8%D9%8A-%D9%8A%D9%8F%D8%B1%D8%A8%D9%83-%D8%AD%D8%B3%D8%A7%D8%A8%D8%A7%D8%AA-%D8%B3%D9%83%D8%A7%D9%84%D9%88%D9%86%D9%8A-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D8%A7%D8%AC%D9%87%D8%A9-%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D9%8A%D9%94%D8%B1/bltd95f750308d8c30a"
            },
            {
                "category": "ألمانيا ضد كوراساو",
                "title": "صافرة عربية لانطلاقة ألمانيا في المونديال",
                "description": "المنتخب الألماني يطمح لتجاوز خيبات الماضي",
                "date": "11 يونيو 2026 22:15",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280912442/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DKMZYHIYA====/GettyImages-2280912442.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B5%D8%A7%D9%81%D8%B1%D8%A9-%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%84%D8%A7%D9%86%D8%B7%D9%84%D8%A7%D9%82%D8%A9-%D8%A7%D9%94%D9%84%D9%85%D8%A7%D9%86%D9%8A%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/bltdf9a4949b1d08ea8"
            },
            {
                "category": "الإنتقالات",
                "title": "تمرد كانسيلو يُقرب نجم برشلونة من الهلال",
                "description": "صفقة تبادلية محتملة",
                "date": "11 يونيو 2026 22:12",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276766997/crop/MM5DGOJUGU5DEMRRHE5G433XMU5DAORSGA2Q====/GettyImages-2276766997.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D9%85%D8%B1%D8%AF-%D9%83%D8%A7%D9%86%D8%B3%D9%8A%D9%84%D9%88-%D9%8A%D9%8F%D9%82%D8%B1%D8%A8-%D9%86%D8%AC%D9%85-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%85%D9%86-%D8%A7%D9%84%D9%87%D9%84%D8%A7%D9%84/blt329f68e13b64deb4"
            },
            {
                "category": "الإنتقالات",
                "title": "تصرفات أتلتيكو مدريد تثير غضب ألفاريز",
                "description": "تصرفات أتلتيكو مدريد تثير غضب ألفاريز",
                "date": "11 يونيو 2026 22:04",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/blte2715a3c2ff60831/crop/MM5DGMZRGI5DCOBWGM5G433XMU5DENRTHI3TCNA=/GettyImages-2274171762.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D8%B5%D8%B1%D9%81%D8%A7%D8%AA-%D8%A7%D9%94%D8%AA%D9%84%D8%AA%D9%8A%D9%83%D9%88-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF-%D8%AA%D8%AB%D9%8A%D8%B1-%D8%BA%D8%B6%D8%A8-%D8%A7%D9%94%D9%84%D9%81%D8%A7%D8%B1%D9%8A%D8%B2/bltbb353af442c1065f"
            },
            {
                "category": "البرازيل ضد المغرب",
                "title": "تصنيف الفيفا: المغرب يتصدر عربيًا وإفريقيًا.. والأرجنتين تنتزع العرش العالمي",
                "description": "راقصو التانجو يستعيدون الصدارة",
                "date": "11 يونيو 2026 21:56",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2279747607/crop/MM5DIOJUHE5DENZYGQ5G433XMU5DAORSHE2Q====/GettyImages-2279747607.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D8%B5%D9%86%D9%8A%D9%81-%D8%A7%D9%84%D9%81%D9%8A%D9%81%D8%A7-%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8-%D9%8A%D8%AA%D8%B5%D8%AF%D8%B1-%D8%B9%D8%B1%D8%A8%D9%8A%D9%8B%D8%A7-%D9%88%D8%A7%D9%95%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D9%8B%D8%A7--%D9%88%D8%A7%D9%84%D8%A7%D9%94%D8%B1%D8%AC%D9%86%D8%AA%D9%8A%D9%86-%D8%AA%D9%86%D8%AA%D8%B2%D8%B9-%D8%A7%D9%84%D8%B9%D8%B1%D8%B4-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85%D9%8A/bltda28cdf225f50c7a"
            },
            {
                "category": "إيران",
                "title": "انفراجة في أزمة التأشيرات.. واشنطن تفتح الباب لمسؤولي إيران مع انطلاق المونديال",
                "description": "قرار أمريكي جديد ",
                "date": "11 يونيو 2026 21:56",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltfebb1c06b1e1cb31/crop/MM5DGOBTHA5DEMJVHE5G433XMU5DAORSGU2Q====/2279691048.jfif",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%86%D9%81%D8%B1%D8%A7%D8%AC%D8%A9-%D9%81%D9%8A-%D8%A7%D9%94%D8%B2%D9%85%D8%A9-%D8%A7%D9%84%D8%AA%D8%A7%D9%94%D8%B4%D9%8A%D8%B1%D8%A7%D8%AA--%D9%88%D8%A7%D8%B4%D9%86%D8%B7%D9%86-%D8%AA%D9%81%D8%AA%D8%AD-%D8%A7%D9%84%D8%A8%D8%A7%D8%A8-%D9%84%D9%85%D8%B3%D9%88%D9%94%D9%88%D9%84%D9%8A-%D8%A7%D9%95%D9%8A%D8%B1%D8%A7%D9%86-%D9%85%D8%B9-%D8%A7%D9%86%D8%B7%D9%84%D8%A7%D9%82-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt4286aacdd22faac8"
            },
            {
                "category": "ليونيل سكالوني",
                "title": "استدعاء متأخر يقتحم قائمة الأرجنتين في كأس العالم",
                "description": "قائمة التانجو تستقبل مدافعا",
                "date": "11 يونيو 2026 21:31",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2268528155/crop/MM5DGMBXGI5DCNZSHA5G433XMU5DCMJ2GA======/GettyImages-2268528155.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B3%D9%83%D8%A7%D9%84%D9%88%D9%86%D9%8A-%D9%8A%D9%81%D8%AC%D8%B1%D9%87%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D9%84%D8%AD%D8%B8%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D8%AE%D9%8A%D8%B1%D8%A9--%D8%A7%D8%B3%D8%AA%D8%AF%D8%B9%D8%A7%D8%A1-%D8%B5%D8%A7%D8%AF%D9%85-%D9%8A%D9%82%D8%AA%D8%AD%D9%85-%D9%82%D8%A7%D9%8A%D9%94%D9%85%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D8%B1%D8%AC%D9%86%D8%AA%D9%8A%D9%86/blta8c437a06029079e"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "مفاجأة في تشكيل المكسيك أمام جنوب أفريقيا",
                "description": "مفاجأة في تشكيل المكسيك أمام جنوب أفريقيا",
                "date": "11 يونيو 2026 21:26",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-1443588631/crop/MM5DCMRYGA5DOMRQHJXG653FHIZTCNJ2GI4TC===/GettyImages-1443588631.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9-%D9%81%D9%8A-%D8%AA%D8%B4%D9%83%D9%8A%D9%84-%D8%A7%D9%84%D9%85%D9%83%D8%B3%D9%8A%D9%83-%D8%A7%D9%94%D9%85%D8%A7%D9%85-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7/blt0dbe6b83eb913a9e"
            },
            {
                "category": "ياسين بونو",
                "title": "رغم الانتقادات.. بونو يحفظ كبرياء الهلال في موسم الصدمة",
                "description": "الأخطبوط المغربي يسطع برقم مثير",
                "date": "11 يونيو 2026 21:24",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2275867891/crop/MM5DCNZTG45DSNZXHJXG653FHIYDUNJYHA======/GettyImages-2275867891.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%BA%D9%85-%D8%A7%D9%84%D8%A7%D9%86%D8%AA%D9%82%D8%A7%D8%AF%D8%A7%D8%AA--%D8%A8%D9%88%D9%86%D9%88-%D9%8A%D8%AD%D9%81%D8%B8-%D9%83%D8%A8%D8%B1%D9%8A%D8%A7%D8%A1-%D8%A7%D9%84%D9%87%D9%84%D8%A7%D9%84-%D9%81%D9%8A-%D9%85%D9%88%D8%B3%D9%85-%D8%A7%D9%84%D8%B5%D8%AF%D9%85%D8%A9/bltffeb5847a6ff4d12"
            },
            {
                "category": "الإنتقالات",
                "title": "سبيشيال وان يعود.. رسميا: مورينيو مدربا لريال مدريد",
                "description": "هل هو الخيار المناسب؟",
                "date": "11 يونيو 2026 21:20",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276020169/crop/MM5DENJRGI5DCNBRGM5G433XMU5DKOJVHIZDSMY=/GettyImages-2276020169.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B3%D8%A8%D9%8A%D8%B4%D9%8A%D8%A7%D9%84-%D9%88%D8%A7%D9%86-%D9%8A%D8%B9%D9%88%D8%AF--%D8%B1%D8%B3%D9%85%D9%8A%D8%A7-%D9%85%D9%88%D8%B1%D9%8A%D9%86%D9%8A%D9%88-%D9%85%D8%AF%D8%B1%D8%A8%D8%A7-%D9%84%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF/blt2ebe9450ab325d3e"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "بعد 40 عامًا.. مفارقة تاريخية تزين افتتاح المونديال",
                "description": "بعد 40 عامًا.. مفارقة تاريخية تزين افتتاح المونديال",
                "date": "11 يونيو 2026 21:04",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280296404/crop/MM5DEMZVGI5DCMZSGM5G433XMU5DIOBXHIZTKMY=/GettyImages-2280296404.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%A8%D8%B9%D8%AF-40-%D8%B9%D8%A7%D9%85%D9%8B%D8%A7--%D9%85%D9%81%D8%A7%D8%B1%D9%82%D8%A9-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A%D8%A9-%D8%AA%D8%B2%D9%8A%D9%86-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt239c8978c95fda08"
            },
            {
                "category": "نواف العقيدي",
                "title": "رغم الإصابة.. دونيس يراهن على العقيدي في كأس العالم",
                "description": "ماذا ينتظر عرين الأخضر في المونديال؟",
                "date": "11 يونيو 2026 21:03",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2206837560/crop/MM5DEOJWGA5DCNRWGU5G433XMU5DCMJ2GA======/GettyImages-2206837560.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%BA%D9%85-%D8%A7%D9%84%D8%A7%D9%95%D8%B5%D8%A7%D8%A8%D8%A9--%D8%AF%D9%88%D9%86%D9%8A%D8%B3-%D9%8A%D8%B1%D8%A7%D9%87%D9%86-%D8%B9%D9%84%D9%89-%D8%A7%D9%84%D8%B9%D9%82%D9%8A%D8%AF%D9%8A-%D9%81%D9%8A-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85/blt2b1efd960f63d3f5"
            },
            {
                "category": "الإنتقالات",
                "title": "جوهرة أفريقية.. الأهلي يبدأ العمل بـ \"قنبلة\" في الميركاتو الصيفي",
                "description": "الراقي يقترب من حسم أولى الصفقات",
                "date": "11 يونيو 2026 21:02",
                "icon": "⚽",
                "type": "local",
                "image": "https://assets.kooora.com/images/v3/getty-2272527235/crop/MM5DGMBZGE5DCNZTHE5G433XMU5DAORRGYYQ====/GettyImages-2272527235.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AC%D9%88%D9%87%D8%B1%D8%A9-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A9--%D8%A7%D9%84%D8%A7%D9%94%D9%87%D9%84%D9%8A-%D9%8A%D8%A8%D8%AF%D8%A7%D9%94-%D8%A7%D9%84%D8%B9%D9%85%D9%84-%D8%A8%D9%80-%D9%82%D9%86%D8%A8%D9%84%D8%A9-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%8A%D8%B1%D9%83%D8%A7%D8%AA%D9%88-%D8%A7%D9%84%D8%B5%D9%8A%D9%81%D9%8A/blt6f07068c253cad97"
            }
        ]
    },
    "ar": {
        "all": [
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "سابقة تاريخية.. المكسيك تكسر عقدتين بعد 96 عامًا",
                "description": "المكسيك بدأت حملتها بنجاح استثنائي",
                "date": "12 يونيو 2026 00:38",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280431821/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2280431821.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B3%D8%A7%D8%A8%D9%82%D8%A9-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A%D8%A9--%D8%A7%D9%84%D9%85%D9%83%D8%B3%D9%8A%D9%83-%D8%AA%D9%83%D8%B3%D8%B1-%D8%B9%D9%82%D8%AF%D8%AA%D9%8A%D9%86-%D8%A8%D8%B9%D8%AF-96-%D8%B9%D8%A7%D9%85%D9%8B%D8%A7/bltdea3b07097298f46"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "افتتاح مونديال 2026 الأكثر احمرارًا في التاريخ",
                "description": "المكسيك استغلت النقص العددي لجنوب إفريقيا",
                "date": "12 يونيو 2026 00:19",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281126711/crop/MM5DGMZTGE5DCOBXGQ5G433XMU5DAORRG42A====/GettyImages-2281126711.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-2026-%D8%A7%D9%84%D8%A7%D9%94%D9%83%D8%AB%D8%B1-%D8%A7%D8%AD%D9%85%D8%B1%D8%A7%D8%B1%D9%8B%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE/bltaab086e20d8ea447"
            },
            {
                "category": "جنوب أفريقيا",
                "title": "بالفيديو.. لعنة إفريقية تضرب افتتاح مونديال 2026",
                "description": "ماذا حدث في مونديال 1990",
                "date": "12 يونيو 2026 00:16",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280453292/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2280453292.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88--%D9%84%D8%B9%D9%86%D8%A9-%D8%A7%D9%84%D9%83%D8%A7%D9%85%D9%8A%D8%B1%D9%88%D9%86-%D8%AA%D8%B6%D8%B1%D8%A8-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%95%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7-%D9%81%D9%8A-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt87f2ad20d3e29e21"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "كينيونيس يدخل تاريخ كأس العالم برقم مذهل",
                "description": "نجم القادسية يصنع الحدث",
                "date": "12 يونيو 2026 00:10",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281123803/crop/MM5DGOJWGA5DEMRSHA5G433XMU5DAORSGA3A====/GettyImages-2281123803.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%83%D9%8A%D9%86%D9%8A%D9%88%D9%86%D9%8A%D8%B3-%D9%8A%D8%AF%D8%AE%D9%84-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-%D8%A8%D8%B1%D9%82%D9%85-%D9%85%D8%B0%D9%87%D9%84/blt6312a8da462a5747"
            },
            {
                "category": "كأس العالم",
                "title": "جدول ترتيب هدافي كأس العالم 2026",
                "description": "تعرف على جدول ترتيب هدافي كأس العالم 2026\n",
                "date": "12 يونيو 2026 00:10",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/blt2a471b58a2988371/GOAL%20-%20Multiple%20Images%20-%204%20Split%20-%20Facebook%20(1).jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AC%D8%AF%D9%88%D9%84-%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D9%87%D8%AF%D8%A7%D9%81%D9%8A-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026/blt322432cc8cc2c1f3"
            },
            {
                "category": "الولايات المتحدة الأمريكية",
                "title": "ترتيب مجموعات كأس العالم 2026 .. جدول المباريات والقنوات الناقلة",
                "description": "تعرف على ترتيب مجموعات بطولة كأس العالم 2026 وجدول المباريات..",
                "date": "12 يونيو 2026 00:09",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2250177089/crop/MM5DKMBQGU5DEOBRGU5G433XMU5DAORSGYYA====/GettyImages-2250177089.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A7%D8%AA-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026-%D8%AC%D8%AF%D9%88%D9%84-%D8%A7%D9%84%D9%85%D8%A8%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D9%82%D9%86%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D9%86%D8%A7%D9%82%D9%84%D8%A9/blt2c98b99c5228b2c9"
            },
            {
                "category": "الولايات المتحدة الأمريكية",
                "title": "جدول مباريات كأس العالم 2026 .. والقنوات الناقلة",
                "description": "تعرف على موعد كأس العالم 2026 وجدول المباريات وترتيب المجموعات والنتائج وجميع القنوات الناقلة للبطولة..",
                "date": "12 يونيو 2026 00:07",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2249518198/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DINZQHIYTAOBT/GettyImages-2249518198.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/-%D8%AC%D8%AF%D9%88%D9%84-%D9%85%D8%A8%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%AA%D8%B1%D8%AA%D9%8A%D8%A8-%D8%A7%D9%84%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A7%D8%AA-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026-%D8%A7%D9%84%D9%82%D9%86%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D9%86%D8%A7%D9%82%D9%84%D8%A9-/blte65707120dfb3330"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "افتتاح أحمر.. المكسيك تدشن المونديال بقهر جنوب أفريقيا",
                "description": "افتتاح أحمر.. المكسيك تدشن المونديال بقهر جنوب أفريقيا",
                "date": "12 يونيو 2026 00:06",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281126711/crop/MM5DEMBQGA5DCMJSGU5G433XMU5DCMJTHA5DEMRR/GettyImages-2281126711.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%94%D8%AD%D9%85%D8%B1--%D8%A7%D9%84%D9%85%D9%83%D8%B3%D9%8A%D9%83-%D8%AA%D8%AF%D8%B4%D9%86-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-%D8%A8%D9%82%D9%87%D8%B1-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7/bltd34abf5688e26504"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "فيديو: دموع الفرح.. خيمينيز يقتل جنوب أفريقيا بهدف تاريخي",
                "description": "هدف يحسم المباراة",
                "date": "12 يونيو 2026 00:01",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltb031673ef03a8e03/crop/MM5DCNZRGI5DSNRTHJXG653FHIYTAMR2GY======/GOAL%20-%20Blank%20WEB%20-%20Facebook%20(31).jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D8%AF%D9%85%D9%88%D8%B9-%D8%A7%D9%84%D9%81%D8%B1%D8%AD--%D8%AE%D9%8A%D9%85%D9%8A%D9%86%D9%8A%D8%B2-%D9%8A%D9%82%D8%AA%D9%84-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7-%D8%A8%D9%87%D8%AF%D9%81-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A/bltfef3d14e8c873360"
            },
            {
                "category": "كأس العالم",
                "title": "جدول مباريات اليوم الجمعة 12 يونيو 2026 في كأس العالم ..القنوات الناقلة والمعلقين",
                "description": "تعرف على مباريات اليوم والقنوات الناقلة وجدول المعلقين\n",
                "date": "12 يونيو 2026 00:00",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltcd07742c13987629/world%20cup%20trophy%20(8).jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AC%D8%AF%D9%88%D9%84-%D9%85%D8%A8%D8%A7%D8%B1%D9%8A%D8%A7%D8%AA-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D8%AC%D9%85%D8%B9%D8%A9-12-%D9%8A%D9%88%D9%86%D9%8A%D9%88-2026-%D9%81%D9%8A-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85--%D8%A7%D9%84%D9%82%D9%86%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D9%86%D8%A7%D9%82%D9%84%D8%A9-%D9%88%D8%A7%D9%84%D9%85%D8%B9%D9%84%D9%82%D9%8A%D9%86/blt07025fc2b907377a"
            },
            {
                "category": "ستال سولباكين",
                "title": "\"كلنا منافقون\".. مدرب النرويج يهز مونديال أمريكا قبل مواجهة العراق",
                "description": "يرفض مع حدث مع المهاجم أيمن حسين",
                "date": "11 يونيو 2026 23:43",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2279518680/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2279518680.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%83%D9%84%D9%86%D8%A7-%D9%85%D9%86%D8%A7%D9%81%D9%82%D9%88%D9%86--%D9%85%D8%AF%D8%B1%D8%A8-%D8%A7%D9%84%D9%86%D8%B1%D9%88%D9%8A%D8%AC-%D9%8A%D9%87%D8%B2-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-%D8%A7%D9%94%D9%85%D8%B1%D9%8A%D9%83%D8%A7-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D8%A7%D8%AC%D9%87%D8%A9-%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82/blt52166b4ee8bf4bdb"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "فيديو: فخ برشلونة يبتلع جنوب أفريقيا في افتتاح كأس العالم 2026",
                "description": "صدمة جديدة تصعق \"البافانا بافانا\"",
                "date": "11 يونيو 2026 23:43",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281122685/crop/MM5DGMBVGQ5DCNZRHA5G433XMU5DAORRGU4Q====/GettyImages-2281122685.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%81%D8%AE-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%8A%D8%A8%D8%AA%D9%84%D8%B9-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7-%D9%81%D9%8A-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85-2026/bltbb3cd963a34b451b"
            },
            {
                "category": "ريال مدريد",
                "title": "ماذا قال برشلونة لبرناردو سيلفا قبل موافقته على عرض ريال مدريد؟",
                "description": "البارسا أوضح ثوابته للبرتغالي",
                "date": "11 يونيو 2026 23:39",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltc8e411517cf48100/crop/MM5DGOJTGY5DEMRRGQ5G433XMU5DAORTGMZA====/GettyImages-2277559471.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D8%A7%D8%B0%D8%A7-%D9%82%D8%A7%D9%84-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%84%D8%A8%D8%B1%D9%86%D8%A7%D8%B1%D8%AF%D9%88-%D8%B3%D9%8A%D9%84%D9%81%D8%A7-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D8%A7%D9%81%D9%82%D8%AA%D9%87-%D8%B9%D9%84%D9%89-%D8%B9%D8%B1%D8%B6-%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF/blt200668ab5ec6b48d"
            },
            {
                "category": "ريال مدريد",
                "title": "تفاصيل الصفقة.. ريال مدريد يتوصل لاتفاق مع برناردو سيلفا",
                "description": "البرتغالي المخضرم بات على أبواب الريال",
                "date": "11 يونيو 2026 23:02",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280476588/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2280476588.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D9%81%D8%A7%D8%B5%D9%8A%D9%84-%D8%A7%D9%84%D8%B5%D9%81%D9%82%D8%A9--%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF-%D9%8A%D8%AA%D9%88%D8%B5%D9%84-%D9%84%D8%A7%D8%AA%D9%81%D8%A7%D9%82-%D9%85%D8%B9-%D8%A8%D8%B1%D9%86%D8%A7%D8%B1%D8%AF%D9%88-%D8%B3%D9%8A%D9%84%D9%81%D8%A7/blt302ed5ba7f79e3a8"
            },
            {
                "category": "المكسيك",
                "title": "بالفيديو: \"دائرة فيفا\" تقتل الخط المعهود.. طقس جديد في مونديال 2026",
                "description": "كيف تم عزف النشيد الوطني في افتتاح كأس العالم؟",
                "date": "11 يونيو 2026 23:00",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281115352/crop/MM5DIOJWGA5DENZZGA5G433XMU5DGMR2GA======/GettyImages-2281115352.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88--%D8%AF%D8%A7%D9%8A%D9%94%D8%B1%D8%A9-%D9%81%D9%8A%D9%81%D8%A7-%D8%AA%D9%82%D8%AA%D9%84-%D8%A7%D9%84%D8%AE%D8%B7-%D8%A7%D9%84%D9%85%D8%B9%D9%87%D9%88%D8%AF--%D8%B7%D9%82%D8%B3-%D8%AC%D8%AF%D9%8A%D8%AF-%D9%81%D9%8A-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-2026/blt050ba69b9547f71a"
            },
            {
                "category": "خوليان كينيونيس",
                "title": "فيديو: من روشن إلى العالم.. كينيونيس يقص شريط أهداف المونديال",
                "description": "نجم المكسيك يسجل أول أهداف المونديال",
                "date": "11 يونيو 2026 22:35",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280535466/crop/MM5DKMBQGM5DEOBRGQ5G433XMU5DAORSGYYQ====/GettyImages-2280535466.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%85%D9%86-%D8%B1%D9%88%D8%B4%D9%86-%D8%A7%D9%95%D9%84%D9%89-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85--%D9%83%D9%8A%D9%86%D9%8A%D9%88%D9%86%D9%8A%D8%B3-%D9%8A%D9%82%D8%B5-%D8%B4%D8%B1%D9%8A%D8%B7-%D8%A7%D9%94%D9%87%D8%AF%D8%A7%D9%81-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt3676342de6ab161c"
            },
            {
                "category": "كأس العالم",
                "title": "بالفيديو.. إنفانتينو يصدم أوروبا: قطر أفضل دولة استضافت المونديال",
                "description": "بالفيديو.. إنفانتينو يصدم أوروبا: قطر أفضل دولة استضافت المونديال",
                "date": "11 يونيو 2026 22:31",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2281117063/crop/MM5DCMRUHA5DOMBSHJXG653FHIYTCNB2GE2DI===/GettyImages-2281117063.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88--%D8%A7%D9%95%D9%86%D9%81%D8%A7%D9%86%D8%AA%D9%8A%D9%86%D9%88-%D9%8A%D8%B5%D8%AF%D9%85-%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D8%A7-%D9%82%D8%B7%D8%B1-%D8%A7%D9%94%D9%81%D8%B6%D9%84-%D8%AF%D9%88%D9%84%D8%A9-%D8%A7%D8%B3%D8%AA%D8%B6%D8%A7%D9%81%D8%AA-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt839e2b330958d567"
            },
            {
                "category": "نيكولاس تاجليافيكو",
                "title": "توتر في معسكر الأرجنتين.. تقرير طبي يُربك حسابات سكالوني قبل مواجهة الجزائر",
                "description": "هل يواجه \"محاربو الصحراء\" دون أحد ركائز \"التانجو\"؟",
                "date": "11 يونيو 2026 22:28",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2267943815/crop/MM5DGNRZGY5DEMBXHE5G433XMU5DAORXGI======/GettyImages-2267943815.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D9%88%D8%AA%D8%B1-%D9%81%D9%8A-%D9%85%D8%B9%D8%B3%D9%83%D8%B1-%D8%A7%D9%84%D8%A7%D9%94%D8%B1%D8%AC%D9%86%D8%AA%D9%8A%D9%86--%D8%AA%D9%82%D8%B1%D9%8A%D8%B1-%D8%B7%D8%A8%D9%8A-%D9%8A%D9%8F%D8%B1%D8%A8%D9%83-%D8%AD%D8%B3%D8%A7%D8%A8%D8%A7%D8%AA-%D8%B3%D9%83%D8%A7%D9%84%D9%88%D9%86%D9%8A-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D8%A7%D8%AC%D9%87%D8%A9-%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D9%8A%D9%94%D8%B1/bltd95f750308d8c30a"
            },
            {
                "category": "ألمانيا ضد كوراساو",
                "title": "صافرة عربية لانطلاقة ألمانيا في المونديال",
                "description": "المنتخب الألماني يطمح لتجاوز خيبات الماضي",
                "date": "11 يونيو 2026 22:15",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280912442/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DKMZYHIYA====/GettyImages-2280912442.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B5%D8%A7%D9%81%D8%B1%D8%A9-%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-%D9%84%D8%A7%D9%86%D8%B7%D9%84%D8%A7%D9%82%D8%A9-%D8%A7%D9%94%D9%84%D9%85%D8%A7%D9%86%D9%8A%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/bltdf9a4949b1d08ea8"
            },
            {
                "category": "الإنتقالات",
                "title": "تمرد كانسيلو يُقرب نجم برشلونة من الهلال",
                "description": "صفقة تبادلية محتملة",
                "date": "11 يونيو 2026 22:12",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276766997/crop/MM5DGOJUGU5DEMRRHE5G433XMU5DAORSGA2Q====/GettyImages-2276766997.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D9%85%D8%B1%D8%AF-%D9%83%D8%A7%D9%86%D8%B3%D9%8A%D9%84%D9%88-%D9%8A%D9%8F%D9%82%D8%B1%D8%A8-%D9%86%D8%AC%D9%85-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%85%D9%86-%D8%A7%D9%84%D9%87%D9%84%D8%A7%D9%84/blt329f68e13b64deb4"
            },
            {
                "category": "الإنتقالات",
                "title": "تصرفات أتلتيكو مدريد تثير غضب ألفاريز",
                "description": "تصرفات أتلتيكو مدريد تثير غضب ألفاريز",
                "date": "11 يونيو 2026 22:04",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/blte2715a3c2ff60831/crop/MM5DGMZRGI5DCOBWGM5G433XMU5DENRTHI3TCNA=/GettyImages-2274171762.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D8%B5%D8%B1%D9%81%D8%A7%D8%AA-%D8%A7%D9%94%D8%AA%D9%84%D8%AA%D9%8A%D9%83%D9%88-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF-%D8%AA%D8%AB%D9%8A%D8%B1-%D8%BA%D8%B6%D8%A8-%D8%A7%D9%94%D9%84%D9%81%D8%A7%D8%B1%D9%8A%D8%B2/bltbb353af442c1065f"
            },
            {
                "category": "البرازيل ضد المغرب",
                "title": "تصنيف الفيفا: المغرب يتصدر عربيًا وإفريقيًا.. والأرجنتين تنتزع العرش العالمي",
                "description": "راقصو التانجو يستعيدون الصدارة",
                "date": "11 يونيو 2026 21:56",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2279747607/crop/MM5DIOJUHE5DENZYGQ5G433XMU5DAORSHE2Q====/GettyImages-2279747607.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D8%B5%D9%86%D9%8A%D9%81-%D8%A7%D9%84%D9%81%D9%8A%D9%81%D8%A7-%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8-%D9%8A%D8%AA%D8%B5%D8%AF%D8%B1-%D8%B9%D8%B1%D8%A8%D9%8A%D9%8B%D8%A7-%D9%88%D8%A7%D9%95%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D9%8B%D8%A7--%D9%88%D8%A7%D9%84%D8%A7%D9%94%D8%B1%D8%AC%D9%86%D8%AA%D9%8A%D9%86-%D8%AA%D9%86%D8%AA%D8%B2%D8%B9-%D8%A7%D9%84%D8%B9%D8%B1%D8%B4-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85%D9%8A/bltda28cdf225f50c7a"
            },
            {
                "category": "إيران",
                "title": "انفراجة في أزمة التأشيرات.. واشنطن تفتح الباب لمسؤولي إيران مع انطلاق المونديال",
                "description": "قرار أمريكي جديد ",
                "date": "11 يونيو 2026 21:56",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/bltfebb1c06b1e1cb31/crop/MM5DGOBTHA5DEMJVHE5G433XMU5DAORSGU2Q====/2279691048.jfif",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%86%D9%81%D8%B1%D8%A7%D8%AC%D8%A9-%D9%81%D9%8A-%D8%A7%D9%94%D8%B2%D9%85%D8%A9-%D8%A7%D9%84%D8%AA%D8%A7%D9%94%D8%B4%D9%8A%D8%B1%D8%A7%D8%AA--%D9%88%D8%A7%D8%B4%D9%86%D8%B7%D9%86-%D8%AA%D9%81%D8%AA%D8%AD-%D8%A7%D9%84%D8%A8%D8%A7%D8%A8-%D9%84%D9%85%D8%B3%D9%88%D9%94%D9%88%D9%84%D9%8A-%D8%A7%D9%95%D9%8A%D8%B1%D8%A7%D9%86-%D9%85%D8%B9-%D8%A7%D9%86%D8%B7%D9%84%D8%A7%D9%82-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt4286aacdd22faac8"
            },
            {
                "category": "ليونيل سكالوني",
                "title": "استدعاء متأخر يقتحم قائمة الأرجنتين في كأس العالم",
                "description": "قائمة التانجو تستقبل مدافعا",
                "date": "11 يونيو 2026 21:31",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2268528155/crop/MM5DGMBXGI5DCNZSHA5G433XMU5DCMJ2GA======/GettyImages-2268528155.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B3%D9%83%D8%A7%D9%84%D9%88%D9%86%D9%8A-%D9%8A%D9%81%D8%AC%D8%B1%D9%87%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D9%84%D8%AD%D8%B8%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D8%AE%D9%8A%D8%B1%D8%A9--%D8%A7%D8%B3%D8%AA%D8%AF%D8%B9%D8%A7%D8%A1-%D8%B5%D8%A7%D8%AF%D9%85-%D9%8A%D9%82%D8%AA%D8%AD%D9%85-%D9%82%D8%A7%D9%8A%D9%94%D9%85%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D8%B1%D8%AC%D9%86%D8%AA%D9%8A%D9%86/blta8c437a06029079e"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "مفاجأة في تشكيل المكسيك أمام جنوب أفريقيا",
                "description": "مفاجأة في تشكيل المكسيك أمام جنوب أفريقيا",
                "date": "11 يونيو 2026 21:26",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-1443588631/crop/MM5DCMRYGA5DOMRQHJXG653FHIZTCNJ2GI4TC===/GettyImages-1443588631.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9-%D9%81%D9%8A-%D8%AA%D8%B4%D9%83%D9%8A%D9%84-%D8%A7%D9%84%D9%85%D9%83%D8%B3%D9%8A%D9%83-%D8%A7%D9%94%D9%85%D8%A7%D9%85-%D8%AC%D9%86%D9%88%D8%A8-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A7/blt0dbe6b83eb913a9e"
            },
            {
                "category": "ياسين بونو",
                "title": "رغم الانتقادات.. بونو يحفظ كبرياء الهلال في موسم الصدمة",
                "description": "الأخطبوط المغربي يسطع برقم مثير",
                "date": "11 يونيو 2026 21:24",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2275867891/crop/MM5DCNZTG45DSNZXHJXG653FHIYDUNJYHA======/GettyImages-2275867891.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%BA%D9%85-%D8%A7%D9%84%D8%A7%D9%86%D8%AA%D9%82%D8%A7%D8%AF%D8%A7%D8%AA--%D8%A8%D9%88%D9%86%D9%88-%D9%8A%D8%AD%D9%81%D8%B8-%D9%83%D8%A8%D8%B1%D9%8A%D8%A7%D8%A1-%D8%A7%D9%84%D9%87%D9%84%D8%A7%D9%84-%D9%81%D9%8A-%D9%85%D9%88%D8%B3%D9%85-%D8%A7%D9%84%D8%B5%D8%AF%D9%85%D8%A9/bltffeb5847a6ff4d12"
            },
            {
                "category": "الإنتقالات",
                "title": "سبيشيال وان يعود.. رسميا: مورينيو مدربا لريال مدريد",
                "description": "هل هو الخيار المناسب؟",
                "date": "11 يونيو 2026 21:20",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276020169/crop/MM5DENJRGI5DCNBRGM5G433XMU5DKOJVHIZDSMY=/GettyImages-2276020169.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B3%D8%A8%D9%8A%D8%B4%D9%8A%D8%A7%D9%84-%D9%88%D8%A7%D9%86-%D9%8A%D8%B9%D9%88%D8%AF--%D8%B1%D8%B3%D9%85%D9%8A%D8%A7-%D9%85%D9%88%D8%B1%D9%8A%D9%86%D9%8A%D9%88-%D9%85%D8%AF%D8%B1%D8%A8%D8%A7-%D9%84%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF/blt2ebe9450ab325d3e"
            },
            {
                "category": "المكسيك ضد جنوب أفريقيا",
                "title": "بعد 40 عامًا.. مفارقة تاريخية تزين افتتاح المونديال",
                "description": "بعد 40 عامًا.. مفارقة تاريخية تزين افتتاح المونديال",
                "date": "11 يونيو 2026 21:04",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2280296404/crop/MM5DEMZVGI5DCMZSGM5G433XMU5DIOBXHIZTKMY=/GettyImages-2280296404.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%A8%D8%B9%D8%AF-40-%D8%B9%D8%A7%D9%85%D9%8B%D8%A7--%D9%85%D9%81%D8%A7%D8%B1%D9%82%D8%A9-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A%D8%A9-%D8%AA%D8%B2%D9%8A%D9%86-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt239c8978c95fda08"
            },
            {
                "category": "نواف العقيدي",
                "title": "رغم الإصابة.. دونيس يراهن على العقيدي في كأس العالم",
                "description": "ماذا ينتظر عرين الأخضر في المونديال؟",
                "date": "11 يونيو 2026 21:03",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2206837560/crop/MM5DEOJWGA5DCNRWGU5G433XMU5DCMJ2GA======/GettyImages-2206837560.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%BA%D9%85-%D8%A7%D9%84%D8%A7%D9%95%D8%B5%D8%A7%D8%A8%D8%A9--%D8%AF%D9%88%D9%86%D9%8A%D8%B3-%D9%8A%D8%B1%D8%A7%D9%87%D9%86-%D8%B9%D9%84%D9%89-%D8%A7%D9%84%D8%B9%D9%82%D9%8A%D8%AF%D9%8A-%D9%81%D9%8A-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85/blt2b1efd960f63d3f5"
            },
            {
                "category": "الإنتقالات",
                "title": "جوهرة أفريقية.. الأهلي يبدأ العمل بـ \"قنبلة\" في الميركاتو الصيفي",
                "description": "الراقي يقترب من حسم أولى الصفقات",
                "date": "11 يونيو 2026 21:02",
                "icon": "⚽",
                "type": "local",
                "image": "https://assets.kooora.com/images/v3/getty-2272527235/crop/MM5DGMBZGE5DCNZTHE5G433XMU5DAORRGYYQ====/GettyImages-2272527235.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AC%D9%88%D9%87%D8%B1%D8%A9-%D8%A7%D9%94%D9%81%D8%B1%D9%8A%D9%82%D9%8A%D8%A9--%D8%A7%D9%84%D8%A7%D9%94%D9%87%D9%84%D9%8A-%D9%8A%D8%A8%D8%AF%D8%A7%D9%94-%D8%A7%D9%84%D8%B9%D9%85%D9%84-%D8%A8%D9%80-%D9%82%D9%86%D8%A8%D9%84%D8%A9-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%8A%D8%B1%D9%83%D8%A7%D8%AA%D9%88-%D8%A7%D9%84%D8%B5%D9%8A%D9%81%D9%8A/blt6f07068c253cad97"
            }
        ]
    }
};

let selectedCategory = 'all';

document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.category-tab').forEach(tab => {
        tab.addEventListener('click', function() {
            document.querySelectorAll('.category-tab').forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            selectedCategory = this.getAttribute('data-category');
            loadNewsContent();
        });
    });
});

function loadNewsContent() {
    const container = document.getElementById('newsGrid');
    if (!container) return;
    let news = newsDatabase[currentLang].all;
    if (selectedCategory !== 'all') news = news.filter(item => item.type === selectedCategory);
    container.innerHTML = '';
    if (news.length === 0) {
        container.innerHTML = `<div style="text-align:center;padding:3rem;color:var(--text-secondary);grid-column:1/-1;"><h3>${currentLang==='en'?'No news found':'لا توجد أخبار'}</h3></div>`;
        return;
    }
    news.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'news-card';
        card.style.animation = `slideUp 0.6s ease-out ${index*0.08}s backwards`;
        const imageHtml = item.image
            ? `<img src="${item.image}" alt="${item.title}" class="news-image-img" loading="lazy" style="width:100%;height:100%;object-fit:cover;" onerror="this.parentElement.innerHTML='<span style=font-size:3rem>📰</span>';">`
            : `<span style="font-size:3rem;">📰</span>`;
        const cardContent = `
            <div class="news-image" style="height:240px;display:flex;align-items:center;justify-content:center;background:rgba(0,102,255,0.1);overflow:hidden;">${imageHtml}</div>
            <div class="news-content">
                <span class="news-category">${item.category}</span>
                <h3 class="news-title">${item.title}</h3>
                <p class="news-description">${item.description||''}</p>
                <div class="news-date">${item.date}</div>
            </div>`;
        if (item.link) {
            const a = document.createElement('a');
            a.href = item.link; a.target = '_blank';
            a.className = 'news-card-link';
            a.style.cssText = 'text-decoration:none;color:inherit;display:block;';
            a.appendChild(card);
            card.innerHTML = cardContent;
            container.appendChild(a);
        } else {
            card.innerHTML = cardContent;
            container.appendChild(card);
        }
    });
}
