// News Database (Auto-generated by KoraLegend Scraper — kooora.com)
// Last updated: 2026-05-30T17:25:46.526Z
const newsDatabase = {
    "en": {
        "all": [
            {
                "category": "فالنسيا ضد رايو فاليكانو",
                "title": "بعد استبعاده من المونديال.. نجم المغرب يودع فريقه",
                "description": "عودة مرتقبة إلى الغواصات الصفراء",
                "date": "30 مايو 2026 20:13",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2164967254/crop/MM5DINRYHA5DENRTG45G433XMU5DCNJUHIZDOMI=/GettyImages-2164967254.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%B9%D8%AF-%D8%A7%D8%B3%D8%AA%D8%A8%D8%B9%D8%A7%D8%AF%D9%87-%D9%85%D9%86-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84--%D9%86%D8%AC%D9%85-%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8-%D9%8A%D9%88%D8%AF%D8%B9-%D9%81%D8%B1%D9%8A%D9%82%D9%87/blt274a82fed626217d"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "\"هدف غير شرعي\".. هل استحق آرسنال التقدم في نهائي دوري الأبطال؟",
                "description": "\"هدف غير شرعي\".. هل استحق آرسنال التقدم في نهائي دوري الأبطال؟",
                "date": "30 مايو 2026 20:08",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278935839/crop/MM5DINRUGA5DENRRGA5G433XMU5DAORSG43Q====/GettyImages-2278935839.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%87%D8%AF%D9%81-%D8%BA%D9%8A%D8%B1-%D8%B4%D8%B1%D8%B9%D9%8A--%D9%87%D9%84-%D8%A7%D8%B3%D8%AA%D8%AD%D9%82-%D8%A7%D9%93%D8%B1%D8%B3%D9%86%D8%A7%D9%84-%D8%A7%D9%84%D8%AA%D9%82%D8%AF%D9%85-%D9%81%D9%8A-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/bltc23950d53a2def38"
            },
            {
                "category": "آرسنال",
                "title": "فأل خير يبشر آرسنال بالنجمة الأولى في دوري الأبطال",
                "description": "عقدة باريس\n",
                "date": "30 مايو 2026 20:03",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278228191/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2278228191.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D8%A7%D9%94%D9%84-%D8%AE%D9%8A%D8%B1-%D9%8A%D8%A8%D8%B4%D8%B1-%D8%A7%D9%93%D8%B1%D8%B3%D9%86%D8%A7%D9%84-%D8%A8%D8%A7%D9%84%D9%86%D8%AC%D9%85%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D9%88%D9%84%D9%89-%D9%81%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/blt8274ef0c0ffa355e"
            },
            {
                "category": "الإنتقالات",
                "title": "مفاجأة أنشيلوتي تؤجل حسم مستقبل إيبانيز مع الأهلي السعودي",
                "description": "المدافع البرازيلي قدم مستويات مميزة مع \"الراقي\"",
                "date": "30 مايو 2026 19:48",
                "icon": "⚽",
                "type": "local",
                "image": "https://assets.kooora.com/images/v3/getty-2278036613/crop/MM5DENJYGY5DCNBVGU5G433XMU5DAORRGM2Q====/GettyImages-2278036613.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9-%D8%A7%D9%94%D9%86%D8%B4%D9%8A%D9%84%D9%88%D8%AA%D9%8A-%D8%AA%D9%88%D9%94%D8%AC%D9%84-%D8%AD%D8%B3%D9%85-%D9%85%D8%B3%D8%AA%D9%82%D8%A8%D9%84-%D8%A7%D9%95%D9%8A%D8%A8%D8%A7%D9%86%D9%8A%D8%B2-%D9%85%D8%B9-%D8%A7%D9%84%D8%A7%D9%94%D9%87%D9%84%D9%8A-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A/blt549a9544a95886cc"
            },
            {
                "category": "المغرب ضد النرويج",
                "title": "خصم المغرب يحقق فوزًا كاسحًا قبل مونديال 2026",
                "description": "القرعة أوقعت المغرب في المجموعة الثالثة",
                "date": "30 مايو 2026 19:40",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2256398763/crop/MM5DGOBSGQ5DEMJVGE5G433XMU5DGMJUHIZTEMQ=/GettyImages-2256398763.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AE%D8%B5%D9%85-%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8-%D9%8A%D8%AD%D9%82%D9%82-%D9%81%D9%88%D8%B2%D9%8B%D8%A7-%D9%83%D8%A7%D8%B3%D8%AD%D9%8B%D8%A7-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-2026/blte4b643ae9a747e7c"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "قرار تاريخي.. إنريكي على خطى زيدان في نهائي الأبطال",
                "description": "تشكيلة ثابتة للعملاق الفرنسي.. هل تتطابق النهاية؟",
                "date": "30 مايو 2026 19:34",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278936677/crop/MM5DINBYGA5DENJSGA5G433XMU5DIORSGI======/GettyImages-2278936677.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%82%D8%B1%D8%A7%D8%B1-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A--%D8%A7%D9%95%D9%86%D8%B1%D9%8A%D9%83%D9%8A-%D8%B9%D9%84%D9%89-%D8%AE%D8%B7%D9%89-%D8%B2%D9%8A%D8%AF%D8%A7%D9%86-%D9%81%D9%8A-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/blt4ac390f739d8c048"
            },
            {
                "category": "الاتحاد",
                "title": "الاتحاد السعودي يحسم أولى صفقات الصيف",
                "description": "العميد يتحرك مُبكرًا",
                "date": "30 مايو 2026 19:32",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2252931732/crop/MM5DGNBVGY5DCOJUGQ5G433XMU5DAORQ/GettyImages-2252931732.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%84%D8%A7%D8%AA%D8%AD%D8%A7%D8%AF-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A-%D9%8A%D8%AD%D8%B3%D9%85-%D8%A7%D9%94%D9%88%D9%84%D9%89-%D8%B5%D9%81%D9%82%D8%A7%D8%AA-%D8%A7%D9%84%D8%B5%D9%8A%D9%81/blta63b095e7c902d44"
            },
            {
                "category": "كاي هافرتيس",
                "title": "بالفيديو: لدغة هافيرتز تسطر تاريخا جديدا في نهائي دوري الأبطال",
                "description": "رجل الأهداف الحاسمة\n",
                "date": "30 مايو 2026 19:29",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278935929/crop/MM5DIOJSGU5DENZXGA5G433XMU5DAORTGEYA====/GettyImages-2278935929.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%84%D8%AF%D8%BA%D8%A9-%D9%87%D8%A7%D9%81%D9%8A%D8%B1%D8%AA%D8%B2-%D8%AA%D8%B3%D8%B7%D8%B1-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D8%A7-%D8%AC%D8%AF%D9%8A%D8%AF%D8%A7-%D9%81%D9%8A-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/blt24cadd6e5035222d"
            },
            {
                "category": "إسبانيول ضد ريال مدريد",
                "title": "بيريز ينقل معركته مع ريكيلمي إلى الجبهة الأوروبية ",
                "description": "بيريز يظهر في المشهد الأوروبي الكبير",
                "date": "30 مايو 2026 19:13",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276275895/crop/MM5DIMJRGY5DEMZRGU5G433XMU5DAORSGM2A====/GettyImages-2276275895.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D9%8A%D8%B1%D9%8A%D8%B2-%D9%8A%D9%86%D9%82%D9%84-%D9%85%D8%B9%D8%B1%D9%83%D8%AA%D9%87-%D9%85%D8%B9-%D8%B1%D9%8A%D9%83%D9%8A%D9%84%D9%85%D9%8A-%D8%A7%D9%95%D9%84%D9%89-%D8%A7%D9%84%D8%AC%D8%A8%D9%87%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D9%8A%D8%A9/blte92a38b1b951312a"
            },
            {
                "category": "آرني سلوت",
                "title": "كواليس الإقالة.. سلوت تفاجأ بالقرار ونجوم ليفربول في صدمة",
                "description": "ماذا حدث؟\n",
                "date": "30 مايو 2026 18:53",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2270858521/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DAORSGA4Q====/GettyImages-2270858521.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%83%D9%88%D8%A7%D9%84%D9%8A%D8%B3-%D8%A7%D9%84%D8%A7%D9%95%D9%82%D8%A7%D9%84%D8%A9--%D8%B3%D9%84%D9%88%D8%AA-%D8%AA%D9%81%D8%A7%D8%AC%D8%A7%D9%94-%D8%A8%D8%A7%D9%84%D9%82%D8%B1%D8%A7%D8%B1-%D9%88%D9%86%D8%AC%D9%88%D9%85-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84-%D9%81%D9%8A-%D8%B5%D8%AF%D9%85%D8%A9/bltf2706029c9da7432"
            },
            {
                "category": "الإنتقالات",
                "title": "الأسرع في تاريخ الدوري الألماني يشعل صراعًا بين روشن والبريميرليج",
                "description": "معارك الميركاتو الصيفي تبدأ مبكرًا",
                "date": "30 مايو 2026 18:51",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2208516748/crop/MM5DINJZGI5DENJYGM5G433XMU5DENZQHI2TAOI=/GettyImages-2208516748.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%84%D8%A7%D9%94%D8%B3%D8%B1%D8%B9-%D9%81%D9%8A-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE-%D8%A7%D9%84%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D9%84%D9%85%D8%A7%D9%86%D9%8A-%D9%8A%D8%B4%D8%B9%D9%84-%D8%B5%D8%B1%D8%A7%D8%B9%D9%8B%D8%A7-%D8%A8%D9%8A%D9%86-%D8%B1%D9%88%D8%B4%D9%86-%D9%88%D8%A7%D9%84%D8%A8%D8%B1%D9%8A%D9%85%D9%8A%D8%B1%D9%84%D9%8A%D8%AC/blt79229224c230160a"
            },
            {
                "category": "مقالات وتقارير",
                "title": "ظهور دونيس الأول.. كيف سيلعب المنتخب السعودي أمام الإكوادور؟",
                "description": "المهمة الأولى للمدرب اليوناني",
                "date": "30 مايو 2026 18:45",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2256731694/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2256731694.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%B8%D9%87%D9%88%D8%B1-%D8%AF%D9%88%D9%86%D9%8A%D8%B3-%D8%A7%D9%84%D8%A7%D9%94%D9%88%D9%84--%D9%83%D9%8A%D9%81-%D8%B3%D9%8A%D9%84%D8%B9%D8%A8-%D8%A7%D9%84%D9%85%D9%86%D8%AA%D8%AE%D8%A8-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A-%D8%A7%D9%94%D9%85%D8%A7%D9%85-%D8%A7%D9%84%D8%A7%D9%95%D9%83%D9%88%D8%A7%D8%AF%D9%88%D8%B1/blt0ce483975c54657a"
            },
            {
                "category": "إسبانيول ضد ريال مدريد",
                "title": "مورينيو لإدارة ريال مدريد: لا أريد نجومًا في الميركاتو",
                "description": "مورينيو يتطلع للروح القتالية أكثر من الأسماء",
                "date": "30 مايو 2026 18:35",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/blt0eed5f15612fa80d/crop/MM5DCMRYGA5DOMRQHJXG653FHIZTEMB2GA======/1600.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%88%D8%B1%D9%8A%D9%86%D9%8A%D9%88-%D9%84%D8%A7%D9%95%D8%AF%D8%A7%D8%B1%D8%A9-%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF-%D9%84%D8%A7-%D8%A7%D9%94%D8%B1%D9%8A%D8%AF-%D9%86%D8%AC%D9%88%D9%85%D9%8B%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%8A%D8%B1%D9%83%D8%A7%D8%AA%D9%88/blte9e8b8e575d4e157"
            },
            {
                "category": "الإنتقالات",
                "title": "رحيل نجم برشلونة مفتاح صفقة كوكوريلا",
                "description": "عيون برشلونة وأتلتيكو تراقب عن كثب",
                "date": "30 مايو 2026 18:33",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2248429051/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2248429051.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%AD%D9%8A%D9%84-%D9%86%D8%AC%D9%85-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%85%D9%81%D8%AA%D8%A7%D8%AD-%D8%B5%D9%81%D9%82%D8%A9-%D9%83%D9%88%D9%83%D9%88%D8%B1%D9%8A%D9%84%D8%A7/blt596da163913dfbba"
            },
            {
                "category": "إيران ضد جامبيا",
                "title": "الاتحاد الإيراني: نشعر بالدهشة مما يحدث.. وطالبنا الفيفا بإجابة قاطعة",
                "description": "الشكوك لا زالت تحيط بالمشاركة الإيرانية",
                "date": "30 مايو 2026 18:20",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2218950168/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2218950168.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%84%D8%A7%D8%AA%D8%AD%D8%A7%D8%AF-%D8%A7%D9%84%D8%A7%D9%95%D9%8A%D8%B1%D8%A7%D9%86%D9%8A-%D9%86%D8%B4%D8%B9%D8%B1-%D8%A8%D8%A7%D9%84%D8%AF%D9%87%D8%B4%D8%A9-%D9%85%D9%85%D8%A7-%D9%8A%D8%AD%D8%AF%D8%AB--%D9%88%D8%B7%D8%A7%D9%84%D8%A8%D9%86%D8%A7-%D8%A7%D9%84%D9%81%D9%8A%D9%81%D8%A7-%D8%A8%D8%A7%D9%95%D8%AC%D8%A7%D8%A8%D8%A9-%D9%82%D8%A7%D8%B7%D8%B9%D8%A9/blt139b96c1fb032cbc"
            },
            {
                "category": "حمزة عبد الكريم",
                "title": "تحت أنظار فليك.. إشادة إسبانية بحصول عبد الكريم على تذكرة المونديال",
                "description": "مستقبل واعد\n",
                "date": "30 مايو 2026 18:18",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2277992050/crop/MM5DGMRRGY5DCOBQHE5G433XMU5DINJQHI2TKOI=/GettyImages-2277992050.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D8%AD%D8%AA-%D8%A7%D9%94%D9%86%D8%B8%D8%A7%D8%B1-%D9%81%D9%84%D9%8A%D9%83--%D8%A7%D9%95%D8%B4%D8%A7%D8%AF%D8%A9-%D8%A7%D9%95%D8%B3%D8%A8%D8%A7%D9%86%D9%8A%D8%A9-%D8%A8%D8%AD%D8%B5%D9%88%D9%84-%D8%B9%D8%A8%D8%AF-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85-%D8%B9%D9%84%D9%89-%D8%AA%D8%B0%D9%83%D8%B1%D8%A9-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt2813f3fa594979c2"
            },
            {
                "category": "الإنتقالات",
                "title": "عمرها أكثر من عام.. نبوءة ميدو عن يايسله تتحول إلى حقيقة",
                "description": "المدرب الألماني قدم نتائج مميزة مع الأهلي",
                "date": "30 مايو 2026 18:15",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2272527100/crop/MM5DENZVGI5DCNJUHA5G433XMU5DEOBQHIYA====/GettyImages-2272527100.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B9%D9%85%D8%B1%D9%87%D8%A7-%D8%A7%D9%94%D9%83%D8%AB%D8%B1-%D9%85%D9%86-%D8%B9%D8%A7%D9%85--%D9%86%D8%A8%D9%88%D8%A1%D8%A9-%D9%85%D9%8A%D8%AF%D9%88-%D8%B9%D9%86-%D9%8A%D8%A7%D9%8A%D8%B3%D9%84%D9%87-%D8%AA%D8%AA%D8%AD%D9%88%D9%84-%D8%A7%D9%95%D9%84%D9%89-%D8%AD%D9%82%D9%8A%D9%82%D8%A9/blte890633b1f4861df"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "موقف حكيمي؟.. التشكيل الرسمي لنهائي دوري أبطال أوروبا",
                "description": "توليفة نارية للفريقين",
                "date": "30 مايو 2026 18:05",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2212716667/crop/MM5DGNJTGY5DCOJYHE5G433XMU5DCMZ2GA======/GettyImages-2212716667.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%88%D9%82%D9%81-%D8%AD%D9%83%D9%8A%D9%85%D9%8A--%D8%A7%D9%84%D8%AA%D8%B4%D9%83%D9%8A%D9%84-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A-%D9%84%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84-%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D8%A7/blta7c2d7d8d0b8198a"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "فيديو: لكمات متبادلة.. معركة شرسة بين جماهير آرسنال وباريس",
                "description": "أكبر حضور في تاريخ شرطة بودابست",
                "date": "30 مايو 2026 17:58",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278924856/crop/MM5DIOJWGY5DENZZGM5G433XMU5DAORRHE4A====/GettyImages-2278924856.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%84%D9%83%D9%85%D8%A7%D8%AA-%D9%85%D8%AA%D8%A8%D8%A7%D8%AF%D9%84%D8%A9--%D9%85%D8%B9%D8%B1%D9%83%D8%A9-%D8%B4%D8%B1%D8%B3%D8%A9-%D8%A8%D9%8A%D9%86-%D8%AC%D9%85%D8%A7%D9%87%D9%8A%D8%B1-%D8%A7%D9%93%D8%B1%D8%B3%D9%86%D8%A7%D9%84-%D9%88%D8%A8%D8%A7%D8%B1%D9%8A%D8%B3/bltc3c65515a85ed92e"
            },
            {
                "category": "حسام عوار",
                "title": "عملاق تركي يستهدف حسام عوار",
                "description": "نجم الجزائر على أعتاب الرحيل",
                "date": "30 مايو 2026 17:57",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2274017741/crop/MM5DINRXGE5DENRSG45G433XMU5DAORSGQ2Q====/GettyImages-2274017741.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B9%D9%85%D9%84%D8%A7%D9%82-%D8%AA%D8%B1%D9%83%D9%8A-%D9%8A%D8%B3%D8%AA%D9%87%D8%AF%D9%81-%D8%AD%D8%B3%D8%A7%D9%85-%D8%B9%D9%88%D8%A7%D8%B1/blted60a4f9f294ae07"
            },
            {
                "category": "الإنتقالات",
                "title": "مفاجأة.. قنبلة صلاح وراء إقالة سلوت من ليفربول",
                "description": "فابريزيو رومانو يكشف الكواليس",
                "date": "30 مايو 2026 17:54",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2277991190/crop/MM5DEMBWGQ5DCMJWGE5G433XMU5DSORTGQ2A====/GettyImages-2277991190.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9--%D9%82%D9%86%D8%A8%D9%84%D8%A9-%D8%B5%D9%84%D8%A7%D8%AD-%D9%88%D8%B1%D8%A7%D8%A1-%D8%A7%D9%95%D9%82%D8%A7%D9%84%D8%A9-%D8%B3%D9%84%D9%88%D8%AA-%D9%85%D9%86-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84/blta032f9775c2d0708"
            },
            {
                "category": "آرني سلوت",
                "title": "عقب الإقالة.. سلوت يقترب من عملاق إيطالي",
                "description": "ميركاتو ساخن\n",
                "date": "30 مايو 2026 17:50",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2273808915/crop/MM5DEMRXGI5DCMRXHA5G433XMU5DKNZXHIYA====/GettyImages-2273808915.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B9%D9%82%D8%A8-%D8%A7%D9%84%D8%A7%D9%95%D9%82%D8%A7%D9%84%D8%A9--%D8%B3%D9%84%D9%88%D8%AA-%D9%8A%D9%82%D8%AA%D8%B1%D8%A8-%D9%85%D9%86-%D8%B9%D9%85%D9%84%D8%A7%D9%82-%D8%A7%D9%95%D9%8A%D8%B7%D8%A7%D9%84%D9%8A/bltd8f33b3b147c521e"
            },
            {
                "category": "الإنتقالات",
                "title": "مفاجأة.. إنزاجي يطالب الهلال بخطف نجم النصر",
                "description": "هل تكون صفقة الموسم؟",
                "date": "30 مايو 2026 17:39",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2269260136/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DKMBQHIYTCMQ=/GettyImages-2269260136.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9--%D8%A7%D9%95%D9%86%D8%B2%D8%A7%D8%AC%D9%8A-%D9%8A%D8%B7%D8%A7%D9%84%D8%A8-%D8%A7%D9%84%D9%87%D9%84%D8%A7%D9%84-%D8%A8%D8%AE%D8%B7%D9%81-%D9%86%D8%AC%D9%85-%D8%A7%D9%84%D9%86%D8%B5%D8%B1/blt044e68c89fa0f8cd"
            },
            {
                "category": "أندوني إيراولا",
                "title": "بديل سلوت.. حقيقة اتفاق ليفربول مع إيراولا",
                "description": "مشروع جديد\n",
                "date": "30 مايو 2026 17:27",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2252861236/crop/MM5DCNRTGI5DSMJYHJXG653FHI3TEORQ/GettyImages-2252861236.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%AF%D9%8A%D9%84-%D8%B3%D9%84%D9%88%D8%AA--%D8%AD%D9%82%D9%8A%D9%82%D8%A9-%D8%A7%D8%AA%D9%81%D8%A7%D9%82-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84-%D9%85%D8%B9-%D8%A7%D9%95%D9%8A%D8%B1%D8%A7%D9%88%D9%84%D8%A7/bltfa5e19395b3789d7"
            },
            {
                "category": "كارلو أنشيلوتي",
                "title": "رد قاطع.. أنشيلوتي يحسم استبعاد نيمار",
                "description": "رد قاطع.. أنشيلوتي يحسم استبعاد نيمار",
                "date": "30 مايو 2026 17:15",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276160103/crop/MM5DIMJZGI5DEMZVHA5G433XMU5DMNJ2GY======/GettyImages-2276160103.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%AF-%D9%82%D8%A7%D8%B7%D8%B9--%D8%A7%D9%94%D9%86%D8%B4%D9%8A%D9%84%D9%88%D8%AA%D9%8A-%D9%8A%D8%AD%D8%B3%D9%85-%D8%A7%D8%B3%D8%AA%D8%A8%D8%B9%D8%A7%D8%AF-%D9%86%D9%8A%D9%85%D8%A7%D8%B1/blt231b3e19bb3eea2d"
            },
            {
                "category": "مقالات وتقارير",
                "title": "الوجه الآخر لمبابي.. عبقرية تصنع المجد وتثير العواصف",
                "description": "أسرار الإمبراطورية التي بناها كيليان \n",
                "date": "30 مايو 2026 17:05",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-1236892681/crop/MM5DKMBQGU5DEOBRGU5G433XMU5DAORSGYYA====/GettyImages-1236892681.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%A7%D9%84%D9%88%D8%AC%D9%87-%D8%A7%D9%84%D8%A7%D9%93%D8%AE%D8%B1-%D9%84%D9%85%D8%A8%D8%A7%D8%A8%D9%8A--%D8%B9%D8%A8%D9%82%D8%B1%D9%8A%D8%A9-%D8%AA%D8%B5%D9%86%D8%B9-%D8%A7%D9%84%D9%85%D8%AC%D8%AF-%D9%88%D8%AA%D8%AB%D9%8A%D8%B1-%D8%A7%D9%84%D8%B9%D9%88%D8%A7%D8%B5%D9%81/blt86d4d0d59d21bfe2"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "لفتة استثنائية من الخليفي قبل نهائي دوري أبطال أوروبا",
                "description": "رسالة ودعوة استثنائية\n",
                "date": "30 مايو 2026 17:03",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278039784/crop/MM5DINZSHA5DENRWGA5G433XMU5DAORSGQ3A====/GettyImages-2278039784.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%84%D9%81%D8%AA%D8%A9-%D8%A7%D8%B3%D8%AA%D8%AB%D9%86%D8%A7%D9%8A%D9%94%D9%8A%D8%A9-%D9%85%D9%86-%D8%A7%D9%84%D8%AE%D9%84%D9%8A%D9%81%D9%8A-%D9%82%D8%A8%D9%84-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84-%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D8%A7/bltd25f6550138aa512"
            },
            {
                "category": "الدوري الإنجليزي الممتاز",
                "title": "نجم السيتي يعترف: جوارديولا أخبرنا بسبب رحيله",
                "description": "نجم السيتي يعترف: جوارديولا أخبرنا بسبب رحيله",
                "date": "30 مايو 2026 16:49",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2277611195/crop/MM5DENRXGI5DCNJQGM5G433XMU5DENRYHIZTKMQ=/GettyImages-2277611195.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%86%D8%AC%D9%85-%D8%A7%D9%84%D8%B3%D9%8A%D8%AA%D9%8A-%D9%8A%D8%B9%D8%AA%D8%B1%D9%81-%D8%AC%D9%88%D8%A7%D8%B1%D8%AF%D9%8A%D9%88%D9%84%D8%A7-%D8%A7%D9%94%D8%AE%D8%A8%D8%B1%D9%86%D8%A7-%D8%A8%D8%B3%D8%A8%D8%A8-%D8%B1%D8%AD%D9%8A%D9%84%D9%87/blt57ac3866b1ca6a36"
            },
            {
                "category": "برشلونة",
                "title": "اقتنع بالأمر الواقع.. جوردون يغلق الباب أمام نجم برشلونة",
                "description": "ما السبب؟",
                "date": "30 مايو 2026 16:30",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278071801/crop/MM5DEOJRGI5DCNRTHA5G433XMU5DCNBYHI3TIOI=/GettyImages-2278071801.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%82%D8%AA%D9%86%D8%B9-%D8%A8%D8%A7%D9%84%D8%A7%D9%94%D9%85%D8%B1-%D8%A7%D9%84%D9%88%D8%A7%D9%82%D8%B9--%D8%AC%D9%88%D8%B1%D8%AF%D9%88%D9%86-%D9%8A%D8%BA%D9%84%D9%82-%D8%A7%D9%84%D8%A8%D8%A7%D8%A8-%D8%A7%D9%94%D9%85%D8%A7%D9%85-%D9%86%D8%AC%D9%85-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9/bltdf9162f5dfee4be6"
            },
            {
                "category": "مصر",
                "title": "مصر تكسر القاعدة.. قرار غير مسبوق يثير الجدل قبل كأس العالم",
                "description": "سابقة تاريخية للفراعنة",
                "date": "30 مايو 2026 16:25",
                "icon": "⚽",
                "type": "local",
                "image": "https://assets.kooora.com/images/v3/getty-2268696285/crop/MM5DINBVHE5DENJQHA5G433XMU5DAORSGMZA====/GettyImages-2268696285.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D8%B5%D8%B1-%D8%AA%D9%83%D8%B3%D8%B1-%D8%A7%D9%84%D9%82%D8%A7%D8%B9%D8%AF%D8%A9--%D9%82%D8%B1%D8%A7%D8%B1-%D8%BA%D9%8A%D8%B1-%D9%85%D8%B3%D8%A8%D9%88%D9%82-%D9%8A%D8%AB%D9%8A%D8%B1-%D8%A7%D9%84%D8%AC%D8%AF%D9%84-%D9%82%D8%A8%D9%84-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85/blt5897c74092fc629c"
            }
        ]
    },
    "ar": {
        "all": [
            {
                "category": "فالنسيا ضد رايو فاليكانو",
                "title": "بعد استبعاده من المونديال.. نجم المغرب يودع فريقه",
                "description": "عودة مرتقبة إلى الغواصات الصفراء",
                "date": "30 مايو 2026 20:13",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2164967254/crop/MM5DINRYHA5DENRTG45G433XMU5DCNJUHIZDOMI=/GettyImages-2164967254.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%B9%D8%AF-%D8%A7%D8%B3%D8%AA%D8%A8%D8%B9%D8%A7%D8%AF%D9%87-%D9%85%D9%86-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84--%D9%86%D8%AC%D9%85-%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8-%D9%8A%D9%88%D8%AF%D8%B9-%D9%81%D8%B1%D9%8A%D9%82%D9%87/blt274a82fed626217d"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "\"هدف غير شرعي\".. هل استحق آرسنال التقدم في نهائي دوري الأبطال؟",
                "description": "\"هدف غير شرعي\".. هل استحق آرسنال التقدم في نهائي دوري الأبطال؟",
                "date": "30 مايو 2026 20:08",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278935839/crop/MM5DINRUGA5DENRRGA5G433XMU5DAORSG43Q====/GettyImages-2278935839.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%87%D8%AF%D9%81-%D8%BA%D9%8A%D8%B1-%D8%B4%D8%B1%D8%B9%D9%8A--%D9%87%D9%84-%D8%A7%D8%B3%D8%AA%D8%AD%D9%82-%D8%A7%D9%93%D8%B1%D8%B3%D9%86%D8%A7%D9%84-%D8%A7%D9%84%D8%AA%D9%82%D8%AF%D9%85-%D9%81%D9%8A-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/bltc23950d53a2def38"
            },
            {
                "category": "آرسنال",
                "title": "فأل خير يبشر آرسنال بالنجمة الأولى في دوري الأبطال",
                "description": "عقدة باريس\n",
                "date": "30 مايو 2026 20:03",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278228191/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2278228191.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D8%A7%D9%94%D9%84-%D8%AE%D9%8A%D8%B1-%D9%8A%D8%A8%D8%B4%D8%B1-%D8%A7%D9%93%D8%B1%D8%B3%D9%86%D8%A7%D9%84-%D8%A8%D8%A7%D9%84%D9%86%D8%AC%D9%85%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D9%88%D9%84%D9%89-%D9%81%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/blt8274ef0c0ffa355e"
            },
            {
                "category": "الإنتقالات",
                "title": "مفاجأة أنشيلوتي تؤجل حسم مستقبل إيبانيز مع الأهلي السعودي",
                "description": "المدافع البرازيلي قدم مستويات مميزة مع \"الراقي\"",
                "date": "30 مايو 2026 19:48",
                "icon": "⚽",
                "type": "local",
                "image": "https://assets.kooora.com/images/v3/getty-2278036613/crop/MM5DENJYGY5DCNBVGU5G433XMU5DAORRGM2Q====/GettyImages-2278036613.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9-%D8%A7%D9%94%D9%86%D8%B4%D9%8A%D9%84%D9%88%D8%AA%D9%8A-%D8%AA%D9%88%D9%94%D8%AC%D9%84-%D8%AD%D8%B3%D9%85-%D9%85%D8%B3%D8%AA%D9%82%D8%A8%D9%84-%D8%A7%D9%95%D9%8A%D8%A8%D8%A7%D9%86%D9%8A%D8%B2-%D9%85%D8%B9-%D8%A7%D9%84%D8%A7%D9%94%D9%87%D9%84%D9%8A-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A/blt549a9544a95886cc"
            },
            {
                "category": "المغرب ضد النرويج",
                "title": "خصم المغرب يحقق فوزًا كاسحًا قبل مونديال 2026",
                "description": "القرعة أوقعت المغرب في المجموعة الثالثة",
                "date": "30 مايو 2026 19:40",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2256398763/crop/MM5DGOBSGQ5DEMJVGE5G433XMU5DGMJUHIZTEMQ=/GettyImages-2256398763.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AE%D8%B5%D9%85-%D8%A7%D9%84%D9%85%D8%BA%D8%B1%D8%A8-%D9%8A%D8%AD%D9%82%D9%82-%D9%81%D9%88%D8%B2%D9%8B%D8%A7-%D9%83%D8%A7%D8%B3%D8%AD%D9%8B%D8%A7-%D9%82%D8%A8%D9%84-%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84-2026/blte4b643ae9a747e7c"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "قرار تاريخي.. إنريكي على خطى زيدان في نهائي الأبطال",
                "description": "تشكيلة ثابتة للعملاق الفرنسي.. هل تتطابق النهاية؟",
                "date": "30 مايو 2026 19:34",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278936677/crop/MM5DINBYGA5DENJSGA5G433XMU5DIORSGI======/GettyImages-2278936677.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%82%D8%B1%D8%A7%D8%B1-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A--%D8%A7%D9%95%D9%86%D8%B1%D9%8A%D9%83%D9%8A-%D8%B9%D9%84%D9%89-%D8%AE%D8%B7%D9%89-%D8%B2%D9%8A%D8%AF%D8%A7%D9%86-%D9%81%D9%8A-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/blt4ac390f739d8c048"
            },
            {
                "category": "الاتحاد",
                "title": "الاتحاد السعودي يحسم أولى صفقات الصيف",
                "description": "العميد يتحرك مُبكرًا",
                "date": "30 مايو 2026 19:32",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2252931732/crop/MM5DGNBVGY5DCOJUGQ5G433XMU5DAORQ/GettyImages-2252931732.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%84%D8%A7%D8%AA%D8%AD%D8%A7%D8%AF-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A-%D9%8A%D8%AD%D8%B3%D9%85-%D8%A7%D9%94%D9%88%D9%84%D9%89-%D8%B5%D9%81%D9%82%D8%A7%D8%AA-%D8%A7%D9%84%D8%B5%D9%8A%D9%81/blta63b095e7c902d44"
            },
            {
                "category": "كاي هافرتيس",
                "title": "بالفيديو: لدغة هافيرتز تسطر تاريخا جديدا في نهائي دوري الأبطال",
                "description": "رجل الأهداف الحاسمة\n",
                "date": "30 مايو 2026 19:29",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278935929/crop/MM5DIOJSGU5DENZXGA5G433XMU5DAORTGEYA====/GettyImages-2278935929.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%A7%D9%84%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%84%D8%AF%D8%BA%D8%A9-%D9%87%D8%A7%D9%81%D9%8A%D8%B1%D8%AA%D8%B2-%D8%AA%D8%B3%D8%B7%D8%B1-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D8%A7-%D8%AC%D8%AF%D9%8A%D8%AF%D8%A7-%D9%81%D9%8A-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84/blt24cadd6e5035222d"
            },
            {
                "category": "إسبانيول ضد ريال مدريد",
                "title": "بيريز ينقل معركته مع ريكيلمي إلى الجبهة الأوروبية ",
                "description": "بيريز يظهر في المشهد الأوروبي الكبير",
                "date": "30 مايو 2026 19:13",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276275895/crop/MM5DIMJRGY5DEMZRGU5G433XMU5DAORSGM2A====/GettyImages-2276275895.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D9%8A%D8%B1%D9%8A%D8%B2-%D9%8A%D9%86%D9%82%D9%84-%D9%85%D8%B9%D8%B1%D9%83%D8%AA%D9%87-%D9%85%D8%B9-%D8%B1%D9%8A%D9%83%D9%8A%D9%84%D9%85%D9%8A-%D8%A7%D9%95%D9%84%D9%89-%D8%A7%D9%84%D8%AC%D8%A8%D9%87%D8%A9-%D8%A7%D9%84%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D9%8A%D8%A9/blte92a38b1b951312a"
            },
            {
                "category": "آرني سلوت",
                "title": "كواليس الإقالة.. سلوت تفاجأ بالقرار ونجوم ليفربول في صدمة",
                "description": "ماذا حدث؟\n",
                "date": "30 مايو 2026 18:53",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2270858521/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DAORSGA4Q====/GettyImages-2270858521.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%83%D9%88%D8%A7%D9%84%D9%8A%D8%B3-%D8%A7%D9%84%D8%A7%D9%95%D9%82%D8%A7%D9%84%D8%A9--%D8%B3%D9%84%D9%88%D8%AA-%D8%AA%D9%81%D8%A7%D8%AC%D8%A7%D9%94-%D8%A8%D8%A7%D9%84%D9%82%D8%B1%D8%A7%D8%B1-%D9%88%D9%86%D8%AC%D9%88%D9%85-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84-%D9%81%D9%8A-%D8%B5%D8%AF%D9%85%D8%A9/bltf2706029c9da7432"
            },
            {
                "category": "الإنتقالات",
                "title": "الأسرع في تاريخ الدوري الألماني يشعل صراعًا بين روشن والبريميرليج",
                "description": "معارك الميركاتو الصيفي تبدأ مبكرًا",
                "date": "30 مايو 2026 18:51",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2208516748/crop/MM5DINJZGI5DENJYGM5G433XMU5DENZQHI2TAOI=/GettyImages-2208516748.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%84%D8%A7%D9%94%D8%B3%D8%B1%D8%B9-%D9%81%D9%8A-%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE-%D8%A7%D9%84%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%84%D8%A7%D9%94%D9%84%D9%85%D8%A7%D9%86%D9%8A-%D9%8A%D8%B4%D8%B9%D9%84-%D8%B5%D8%B1%D8%A7%D8%B9%D9%8B%D8%A7-%D8%A8%D9%8A%D9%86-%D8%B1%D9%88%D8%B4%D9%86-%D9%88%D8%A7%D9%84%D8%A8%D8%B1%D9%8A%D9%85%D9%8A%D8%B1%D9%84%D9%8A%D8%AC/blt79229224c230160a"
            },
            {
                "category": "مقالات وتقارير",
                "title": "ظهور دونيس الأول.. كيف سيلعب المنتخب السعودي أمام الإكوادور؟",
                "description": "المهمة الأولى للمدرب اليوناني",
                "date": "30 مايو 2026 18:45",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2256731694/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2256731694.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%B8%D9%87%D9%88%D8%B1-%D8%AF%D9%88%D9%86%D9%8A%D8%B3-%D8%A7%D9%84%D8%A7%D9%94%D9%88%D9%84--%D9%83%D9%8A%D9%81-%D8%B3%D9%8A%D9%84%D8%B9%D8%A8-%D8%A7%D9%84%D9%85%D9%86%D8%AA%D8%AE%D8%A8-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A-%D8%A7%D9%94%D9%85%D8%A7%D9%85-%D8%A7%D9%84%D8%A7%D9%95%D9%83%D9%88%D8%A7%D8%AF%D9%88%D8%B1/blt0ce483975c54657a"
            },
            {
                "category": "إسبانيول ضد ريال مدريد",
                "title": "مورينيو لإدارة ريال مدريد: لا أريد نجومًا في الميركاتو",
                "description": "مورينيو يتطلع للروح القتالية أكثر من الأسماء",
                "date": "30 مايو 2026 18:35",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/blt0eed5f15612fa80d/crop/MM5DCMRYGA5DOMRQHJXG653FHIZTEMB2GA======/1600.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%88%D8%B1%D9%8A%D9%86%D9%8A%D9%88-%D9%84%D8%A7%D9%95%D8%AF%D8%A7%D8%B1%D8%A9-%D8%B1%D9%8A%D8%A7%D9%84-%D9%85%D8%AF%D8%B1%D9%8A%D8%AF-%D9%84%D8%A7-%D8%A7%D9%94%D8%B1%D9%8A%D8%AF-%D9%86%D8%AC%D9%88%D9%85%D9%8B%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D9%8A%D8%B1%D9%83%D8%A7%D8%AA%D9%88/blte9e8b8e575d4e157"
            },
            {
                "category": "الإنتقالات",
                "title": "رحيل نجم برشلونة مفتاح صفقة كوكوريلا",
                "description": "عيون برشلونة وأتلتيكو تراقب عن كثب",
                "date": "30 مايو 2026 18:33",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2248429051/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2248429051.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%AD%D9%8A%D9%84-%D9%86%D8%AC%D9%85-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9-%D9%85%D9%81%D8%AA%D8%A7%D8%AD-%D8%B5%D9%81%D9%82%D8%A9-%D9%83%D9%88%D9%83%D9%88%D8%B1%D9%8A%D9%84%D8%A7/blt596da163913dfbba"
            },
            {
                "category": "إيران ضد جامبيا",
                "title": "الاتحاد الإيراني: نشعر بالدهشة مما يحدث.. وطالبنا الفيفا بإجابة قاطعة",
                "description": "الشكوك لا زالت تحيط بالمشاركة الإيرانية",
                "date": "30 مايو 2026 18:20",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2218950168/crop/MM5DKMBQGQ5DEOBRGU5G433XMU5DAORSGYYQ====/GettyImages-2218950168.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%84%D8%A7%D8%AA%D8%AD%D8%A7%D8%AF-%D8%A7%D9%84%D8%A7%D9%95%D9%8A%D8%B1%D8%A7%D9%86%D9%8A-%D9%86%D8%B4%D8%B9%D8%B1-%D8%A8%D8%A7%D9%84%D8%AF%D9%87%D8%B4%D8%A9-%D9%85%D9%85%D8%A7-%D9%8A%D8%AD%D8%AF%D8%AB--%D9%88%D8%B7%D8%A7%D9%84%D8%A8%D9%86%D8%A7-%D8%A7%D9%84%D9%81%D9%8A%D9%81%D8%A7-%D8%A8%D8%A7%D9%95%D8%AC%D8%A7%D8%A8%D8%A9-%D9%82%D8%A7%D8%B7%D8%B9%D8%A9/blt139b96c1fb032cbc"
            },
            {
                "category": "حمزة عبد الكريم",
                "title": "تحت أنظار فليك.. إشادة إسبانية بحصول عبد الكريم على تذكرة المونديال",
                "description": "مستقبل واعد\n",
                "date": "30 مايو 2026 18:18",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2277992050/crop/MM5DGMRRGY5DCOBQHE5G433XMU5DINJQHI2TKOI=/GettyImages-2277992050.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%AA%D8%AD%D8%AA-%D8%A7%D9%94%D9%86%D8%B8%D8%A7%D8%B1-%D9%81%D9%84%D9%8A%D9%83--%D8%A7%D9%95%D8%B4%D8%A7%D8%AF%D8%A9-%D8%A7%D9%95%D8%B3%D8%A8%D8%A7%D9%86%D9%8A%D8%A9-%D8%A8%D8%AD%D8%B5%D9%88%D9%84-%D8%B9%D8%A8%D8%AF-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85-%D8%B9%D9%84%D9%89-%D8%AA%D8%B0%D9%83%D8%B1%D8%A9-%D8%A7%D9%84%D9%85%D9%88%D9%86%D8%AF%D9%8A%D8%A7%D9%84/blt2813f3fa594979c2"
            },
            {
                "category": "الإنتقالات",
                "title": "عمرها أكثر من عام.. نبوءة ميدو عن يايسله تتحول إلى حقيقة",
                "description": "المدرب الألماني قدم نتائج مميزة مع الأهلي",
                "date": "30 مايو 2026 18:15",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2272527100/crop/MM5DENZVGI5DCNJUHA5G433XMU5DEOBQHIYA====/GettyImages-2272527100.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B9%D9%85%D8%B1%D9%87%D8%A7-%D8%A7%D9%94%D9%83%D8%AB%D8%B1-%D9%85%D9%86-%D8%B9%D8%A7%D9%85--%D9%86%D8%A8%D9%88%D8%A1%D8%A9-%D9%85%D9%8A%D8%AF%D9%88-%D8%B9%D9%86-%D9%8A%D8%A7%D9%8A%D8%B3%D9%84%D9%87-%D8%AA%D8%AA%D8%AD%D9%88%D9%84-%D8%A7%D9%95%D9%84%D9%89-%D8%AD%D9%82%D9%8A%D9%82%D8%A9/blte890633b1f4861df"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "موقف حكيمي؟.. التشكيل الرسمي لنهائي دوري أبطال أوروبا",
                "description": "توليفة نارية للفريقين",
                "date": "30 مايو 2026 18:05",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2212716667/crop/MM5DGNJTGY5DCOJYHE5G433XMU5DCMZ2GA======/GettyImages-2212716667.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%88%D9%82%D9%81-%D8%AD%D9%83%D9%8A%D9%85%D9%8A--%D8%A7%D9%84%D8%AA%D8%B4%D9%83%D9%8A%D9%84-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A-%D9%84%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84-%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D8%A7/blta7c2d7d8d0b8198a"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "فيديو: لكمات متبادلة.. معركة شرسة بين جماهير آرسنال وباريس",
                "description": "أكبر حضور في تاريخ شرطة بودابست",
                "date": "30 مايو 2026 17:58",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278924856/crop/MM5DIOJWGY5DENZZGM5G433XMU5DAORRHE4A====/GettyImages-2278924856.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%8A%D8%AF%D9%8A%D9%88-%D9%84%D9%83%D9%85%D8%A7%D8%AA-%D9%85%D8%AA%D8%A8%D8%A7%D8%AF%D9%84%D8%A9--%D9%85%D8%B9%D8%B1%D9%83%D8%A9-%D8%B4%D8%B1%D8%B3%D8%A9-%D8%A8%D9%8A%D9%86-%D8%AC%D9%85%D8%A7%D9%87%D9%8A%D8%B1-%D8%A7%D9%93%D8%B1%D8%B3%D9%86%D8%A7%D9%84-%D9%88%D8%A8%D8%A7%D8%B1%D9%8A%D8%B3/bltc3c65515a85ed92e"
            },
            {
                "category": "حسام عوار",
                "title": "عملاق تركي يستهدف حسام عوار",
                "description": "نجم الجزائر على أعتاب الرحيل",
                "date": "30 مايو 2026 17:57",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2274017741/crop/MM5DINRXGE5DENRSG45G433XMU5DAORSGQ2Q====/GettyImages-2274017741.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B9%D9%85%D9%84%D8%A7%D9%82-%D8%AA%D8%B1%D9%83%D9%8A-%D9%8A%D8%B3%D8%AA%D9%87%D8%AF%D9%81-%D8%AD%D8%B3%D8%A7%D9%85-%D8%B9%D9%88%D8%A7%D8%B1/blted60a4f9f294ae07"
            },
            {
                "category": "الإنتقالات",
                "title": "مفاجأة.. قنبلة صلاح وراء إقالة سلوت من ليفربول",
                "description": "فابريزيو رومانو يكشف الكواليس",
                "date": "30 مايو 2026 17:54",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2277991190/crop/MM5DEMBWGQ5DCMJWGE5G433XMU5DSORTGQ2A====/GettyImages-2277991190.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9--%D9%82%D9%86%D8%A8%D9%84%D8%A9-%D8%B5%D9%84%D8%A7%D8%AD-%D9%88%D8%B1%D8%A7%D8%A1-%D8%A7%D9%95%D9%82%D8%A7%D9%84%D8%A9-%D8%B3%D9%84%D9%88%D8%AA-%D9%85%D9%86-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84/blta032f9775c2d0708"
            },
            {
                "category": "آرني سلوت",
                "title": "عقب الإقالة.. سلوت يقترب من عملاق إيطالي",
                "description": "ميركاتو ساخن\n",
                "date": "30 مايو 2026 17:50",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2273808915/crop/MM5DEMRXGI5DCMRXHA5G433XMU5DKNZXHIYA====/GettyImages-2273808915.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B9%D9%82%D8%A8-%D8%A7%D9%84%D8%A7%D9%95%D9%82%D8%A7%D9%84%D8%A9--%D8%B3%D9%84%D9%88%D8%AA-%D9%8A%D9%82%D8%AA%D8%B1%D8%A8-%D9%85%D9%86-%D8%B9%D9%85%D9%84%D8%A7%D9%82-%D8%A7%D9%95%D9%8A%D8%B7%D8%A7%D9%84%D9%8A/bltd8f33b3b147c521e"
            },
            {
                "category": "الإنتقالات",
                "title": "مفاجأة.. إنزاجي يطالب الهلال بخطف نجم النصر",
                "description": "هل تكون صفقة الموسم؟",
                "date": "30 مايو 2026 17:39",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2269260136/crop/MM5DIMBQGA5DEMRVGA5G433XMU5DKMBQHIYTCMQ=/GettyImages-2269260136.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D9%81%D8%A7%D8%AC%D8%A7%D9%94%D8%A9--%D8%A7%D9%95%D9%86%D8%B2%D8%A7%D8%AC%D9%8A-%D9%8A%D8%B7%D8%A7%D9%84%D8%A8-%D8%A7%D9%84%D9%87%D9%84%D8%A7%D9%84-%D8%A8%D8%AE%D8%B7%D9%81-%D9%86%D8%AC%D9%85-%D8%A7%D9%84%D9%86%D8%B5%D8%B1/blt044e68c89fa0f8cd"
            },
            {
                "category": "أندوني إيراولا",
                "title": "بديل سلوت.. حقيقة اتفاق ليفربول مع إيراولا",
                "description": "مشروع جديد\n",
                "date": "30 مايو 2026 17:27",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2252861236/crop/MM5DCNRTGI5DSMJYHJXG653FHI3TEORQ/GettyImages-2252861236.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A8%D8%AF%D9%8A%D9%84-%D8%B3%D9%84%D9%88%D8%AA--%D8%AD%D9%82%D9%8A%D9%82%D8%A9-%D8%A7%D8%AA%D9%81%D8%A7%D9%82-%D9%84%D9%8A%D9%81%D8%B1%D8%A8%D9%88%D9%84-%D9%85%D8%B9-%D8%A7%D9%95%D9%8A%D8%B1%D8%A7%D9%88%D9%84%D8%A7/bltfa5e19395b3789d7"
            },
            {
                "category": "كارلو أنشيلوتي",
                "title": "رد قاطع.. أنشيلوتي يحسم استبعاد نيمار",
                "description": "رد قاطع.. أنشيلوتي يحسم استبعاد نيمار",
                "date": "30 مايو 2026 17:15",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2276160103/crop/MM5DIMJZGI5DEMZVHA5G433XMU5DMNJ2GY======/GettyImages-2276160103.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B1%D8%AF-%D9%82%D8%A7%D8%B7%D8%B9--%D8%A7%D9%94%D9%86%D8%B4%D9%8A%D9%84%D9%88%D8%AA%D9%8A-%D9%8A%D8%AD%D8%B3%D9%85-%D8%A7%D8%B3%D8%AA%D8%A8%D8%B9%D8%A7%D8%AF-%D9%86%D9%8A%D9%85%D8%A7%D8%B1/blt231b3e19bb3eea2d"
            },
            {
                "category": "مقالات وتقارير",
                "title": "الوجه الآخر لمبابي.. عبقرية تصنع المجد وتثير العواصف",
                "description": "أسرار الإمبراطورية التي بناها كيليان \n",
                "date": "30 مايو 2026 17:05",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-1236892681/crop/MM5DKMBQGU5DEOBRGU5G433XMU5DAORSGYYA====/GettyImages-1236892681.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D8%A6%D9%85/%D8%A7%D9%84%D9%88%D8%AC%D9%87-%D8%A7%D9%84%D8%A7%D9%93%D8%AE%D8%B1-%D9%84%D9%85%D8%A8%D8%A7%D8%A8%D9%8A--%D8%B9%D8%A8%D9%82%D8%B1%D9%8A%D8%A9-%D8%AA%D8%B5%D9%86%D8%B9-%D8%A7%D9%84%D9%85%D8%AC%D8%AF-%D9%88%D8%AA%D8%AB%D9%8A%D8%B1-%D8%A7%D9%84%D8%B9%D9%88%D8%A7%D8%B5%D9%81/blt86d4d0d59d21bfe2"
            },
            {
                "category": "باريس سان جيرمان ضد آرسنال",
                "title": "لفتة استثنائية من الخليفي قبل نهائي دوري أبطال أوروبا",
                "description": "رسالة ودعوة استثنائية\n",
                "date": "30 مايو 2026 17:03",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278039784/crop/MM5DINZSHA5DENRWGA5G433XMU5DAORSGQ3A====/GettyImages-2278039784.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%84%D9%81%D8%AA%D8%A9-%D8%A7%D8%B3%D8%AA%D8%AB%D9%86%D8%A7%D9%8A%D9%94%D9%8A%D8%A9-%D9%85%D9%86-%D8%A7%D9%84%D8%AE%D9%84%D9%8A%D9%81%D9%8A-%D9%82%D8%A8%D9%84-%D9%86%D9%87%D8%A7%D9%8A%D9%94%D9%8A-%D8%AF%D9%88%D8%B1%D9%8A-%D8%A7%D9%94%D8%A8%D8%B7%D8%A7%D9%84-%D8%A7%D9%94%D9%88%D8%B1%D9%88%D8%A8%D8%A7/bltd25f6550138aa512"
            },
            {
                "category": "الدوري الإنجليزي الممتاز",
                "title": "نجم السيتي يعترف: جوارديولا أخبرنا بسبب رحيله",
                "description": "نجم السيتي يعترف: جوارديولا أخبرنا بسبب رحيله",
                "date": "30 مايو 2026 16:49",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2277611195/crop/MM5DENRXGI5DCNJQGM5G433XMU5DENRYHIZTKMQ=/GettyImages-2277611195.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%86%D8%AC%D9%85-%D8%A7%D9%84%D8%B3%D9%8A%D8%AA%D9%8A-%D9%8A%D8%B9%D8%AA%D8%B1%D9%81-%D8%AC%D9%88%D8%A7%D8%B1%D8%AF%D9%8A%D9%88%D9%84%D8%A7-%D8%A7%D9%94%D8%AE%D8%A8%D8%B1%D9%86%D8%A7-%D8%A8%D8%B3%D8%A8%D8%A8-%D8%B1%D8%AD%D9%8A%D9%84%D9%87/blt57ac3866b1ca6a36"
            },
            {
                "category": "برشلونة",
                "title": "اقتنع بالأمر الواقع.. جوردون يغلق الباب أمام نجم برشلونة",
                "description": "ما السبب؟",
                "date": "30 مايو 2026 16:30",
                "icon": "🌍",
                "type": "international",
                "image": "https://assets.kooora.com/images/v3/getty-2278071801/crop/MM5DEOJRGI5DCNRTHA5G433XMU5DCNBYHI3TIOI=/GettyImages-2278071801.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D8%A7%D9%82%D8%AA%D9%86%D8%B9-%D8%A8%D8%A7%D9%84%D8%A7%D9%94%D9%85%D8%B1-%D8%A7%D9%84%D9%88%D8%A7%D9%82%D8%B9--%D8%AC%D9%88%D8%B1%D8%AF%D9%88%D9%86-%D9%8A%D8%BA%D9%84%D9%82-%D8%A7%D9%84%D8%A8%D8%A7%D8%A8-%D8%A7%D9%94%D9%85%D8%A7%D9%85-%D9%86%D8%AC%D9%85-%D8%A8%D8%B1%D8%B4%D9%84%D9%88%D9%86%D8%A9/bltdf9162f5dfee4be6"
            },
            {
                "category": "مصر",
                "title": "مصر تكسر القاعدة.. قرار غير مسبوق يثير الجدل قبل كأس العالم",
                "description": "سابقة تاريخية للفراعنة",
                "date": "30 مايو 2026 16:25",
                "icon": "⚽",
                "type": "local",
                "image": "https://assets.kooora.com/images/v3/getty-2268696285/crop/MM5DINBVHE5DENJQHA5G433XMU5DAORSGMZA====/GettyImages-2268696285.jpg",
                "link": "https://www.kooora.com/%D9%83%D8%B1%D8%A9-%D9%82%D8%AF%D9%85/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/%D9%85%D8%B5%D8%B1-%D8%AA%D9%83%D8%B3%D8%B1-%D8%A7%D9%84%D9%82%D8%A7%D8%B9%D8%AF%D8%A9--%D9%82%D8%B1%D8%A7%D8%B1-%D8%BA%D9%8A%D8%B1-%D9%85%D8%B3%D8%A8%D9%88%D9%82-%D9%8A%D8%AB%D9%8A%D8%B1-%D8%A7%D9%84%D8%AC%D8%AF%D9%84-%D9%82%D8%A8%D9%84-%D9%83%D8%A7%D9%94%D8%B3-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85/blt5897c74092fc629c"
            }
        ]
    }
};

let selectedCategory = 'all';

document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.category-tab').forEach(tab => {
        tab.addEventListener('click', function() {
            document.querySelectorAll('.category-tab').forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            selectedCategory = this.getAttribute('data-category');
            loadNewsContent();
        });
    });
});

function loadNewsContent() {
    const container = document.getElementById('newsGrid');
    if (!container) return;
    let news = newsDatabase[currentLang].all;
    if (selectedCategory !== 'all') news = news.filter(item => item.type === selectedCategory);
    container.innerHTML = '';
    if (news.length === 0) {
        container.innerHTML = `<div style="text-align:center;padding:3rem;color:var(--text-secondary);grid-column:1/-1;"><h3>${currentLang==='en'?'No news found':'لا توجد أخبار'}</h3></div>`;
        return;
    }
    news.forEach((item, index) => {
        const card = document.createElement('div');
        card.className = 'news-card';
        card.style.animation = `slideUp 0.6s ease-out ${index*0.08}s backwards`;
        const imageHtml = item.image
            ? `<img src="${item.image}" alt="${item.title}" class="news-image-img" loading="lazy" style="width:100%;height:100%;object-fit:cover;" onerror="this.parentElement.innerHTML='<span style=font-size:3rem>📰</span>';">`
            : `<span style="font-size:3rem;">📰</span>`;
        const cardContent = `
            <div class="news-image" style="height:240px;display:flex;align-items:center;justify-content:center;background:rgba(0,102,255,0.1);overflow:hidden;">${imageHtml}</div>
            <div class="news-content">
                <span class="news-category">${item.category}</span>
                <h3 class="news-title">${item.title}</h3>
                <p class="news-description">${item.description||''}</p>
                <div class="news-date">${item.date}</div>
            </div>`;
        if (item.link) {
            const a = document.createElement('a');
            a.href = item.link; a.target = '_blank';
            a.className = 'news-card-link';
            a.style.cssText = 'text-decoration:none;color:inherit;display:block;';
            a.appendChild(card);
            card.innerHTML = cardContent;
            container.appendChild(a);
        } else {
            card.innerHTML = cardContent;
            container.appendChild(card);
        }
    });
}
